"""Alembic environment — async, driven by application settings.

Two things worth knowing:

1. Migrations run against **DIRECT_URL** (Neon's unpooled endpoint), never
   DATABASE_URL. PgBouncer in transaction mode breaks the session-scoped
   advisory lock Alembic uses and can split a DDL transaction across server
   connections — both silent corruption risks. The app uses the pooled
   endpoint; migrations use the direct one.

2. Table metadata comes from `app.registry`, which is the one place every
   module's models get imported. If a new table does not appear in an
   autogenerated migration, it is missing from that file.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import Connection

from app.core.database import create_engine
from app.registry import target_metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Catch column type changes, not just added/dropped columns.
        compare_type=True,
        compare_server_default=True,
        # Deterministic constraint names come from the naming convention set in
        # app.core.models; pass it through so autogenerate agrees with the DB.
        render_as_batch=False,
        include_schemas=False,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting (`alembic upgrade head --sql`)."""
    from app.core.config import settings

    context.configure(
        url=settings.async_direct_url.render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    engine = create_engine(direct=True)
    try:
        async with engine.connect() as connection:
            await connection.run_sync(_run_migrations)
            await connection.commit()
    finally:
        await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
