"""clinical schema

Revision ID: 5bb9e496ac94
Revises: 65de4faabe4f
Create Date: 2026-08-08 10:56:40.598994+00:00

The Encounter and everything hung off it: the state-change audit trail
(`encounter_events`), vitals, clinical notes and their templates, diagnoses, and
the order ledger that decides when a visit may close.

Row-level security and this module's permission seed land in the migration that
follows, on the pattern the identity, patients and scheduling migrations set.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5bb9e496ac94"
down_revision: str | None = "65de4faabe4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "encounter_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_encounter_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encounter_sequences")),
    )
    op.create_index(
        op.f("ix_encounter_sequences_hospital_id"),
        "encounter_sequences",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_encounter_sequences_year"), "encounter_sequences", ["year"], unique=False
    )
    op.create_index(
        "uq_encounter_sequences_hospital_year",
        "encounter_sequences",
        ["hospital_id", "year"],
        unique=True,
    )
    op.create_table(
        "note_templates",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column(
            "template_type",
            sa.Enum(
                "NOTE",
                "DIAGNOSIS",
                "PRESCRIPTION",
                "ADVICE",
                "FOLLOW_UP",
                "ORDER_SET",
                name="templatetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "note_type",
            sa.Enum(
                "CHIEF_COMPLAINT",
                "HISTORY",
                "EXAMINATION",
                "ASSESSMENT",
                "PLAN",
                "ADVICE",
                "PROGRESS",
                "NURSING",
                name="notetype",
            ),
            nullable=True,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_note_templates_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_note_templates_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_note_templates_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_templates")),
    )
    op.create_index(
        op.f("ix_note_templates_deleted_at"), "note_templates", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_note_templates_hospital_id"), "note_templates", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_note_templates_hospital_id_template_type",
        "note_templates",
        ["hospital_id", "template_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_templates_is_active"), "note_templates", ["is_active"], unique=False
    )
    op.create_index(
        "ix_note_templates_owner_id_is_active",
        "note_templates",
        ["owner_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_templates_template_type"), "note_templates", ["template_type"], unique=False
    )
    op.create_index(op.f("ix_note_templates_title"), "note_templates", ["title"], unique=False)
    op.create_table(
        "encounters",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("doctor_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column(
            "encounter_type",
            sa.Enum("OPD", "EMERGENCY", "IPD", "DAY_CARE", name="encountertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "REGISTERED",
                "IN_CONSULTATION",
                "AWAITING_RESULTS",
                "PENDING_CLEARANCE",
                "ADMITTED",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                "REFERRED_OUT",
                "LAMA",
                "DECEASED",
                name="encounterstatus",
            ),
            nullable=False,
        ),
        sa.Column("chief_complaint", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("triage_note", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consultation_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consultation_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by_id", sa.Uuid(), nullable=True),
        sa.Column("closed_automatically", sa.Boolean(), nullable=False),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column(
            "follow_up_instructions", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("deceased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("death_certified_by_id", sa.Uuid(), nullable=True),
        sa.Column("cause_of_death", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("death_place", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("referred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "referred_to_facility", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("referral_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("referral_transport", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("lama_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lama_recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("lama_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("lama_form_signed", sa.Boolean(), nullable=False),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_encounters_appointment_id_appointments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_id"],
            ["users.id"],
            name=op.f("fk_encounters_closed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["death_certified_by_id"],
            ["users.id"],
            name=op.f("fk_encounters_death_certified_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_encounters_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_encounters_doctor_id_doctors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_encounters_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lama_recorded_by_id"],
            ["users.id"],
            name=op.f("fk_encounters_lama_recorded_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_encounters_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encounters")),
    )
    op.create_index(
        op.f("ix_encounters_appointment_id"), "encounters", ["appointment_id"], unique=False
    )
    op.create_index(op.f("ix_encounters_deleted_at"), "encounters", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_encounters_department_id"), "encounters", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_encounters_doctor_id"), "encounters", ["doctor_id"], unique=False)
    op.create_index(
        "ix_encounters_doctor_id_status", "encounters", ["doctor_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_encounters_encounter_number"), "encounters", ["encounter_number"], unique=False
    )
    op.create_index(
        op.f("ix_encounters_encounter_type"), "encounters", ["encounter_type"], unique=False
    )
    op.create_index(
        op.f("ix_encounters_follow_up_date"), "encounters", ["follow_up_date"], unique=False
    )
    op.create_index(op.f("ix_encounters_hospital_id"), "encounters", ["hospital_id"], unique=False)
    op.create_index(
        "ix_encounters_hospital_id_status", "encounters", ["hospital_id", "status"], unique=False
    )
    op.create_index(op.f("ix_encounters_patient_id"), "encounters", ["patient_id"], unique=False)
    op.create_index(
        "ix_encounters_patient_id_started_at",
        "encounters",
        ["patient_id", "started_at"],
        unique=False,
    )
    op.create_index(op.f("ix_encounters_started_at"), "encounters", ["started_at"], unique=False)
    op.create_index(op.f("ix_encounters_status"), "encounters", ["status"], unique=False)
    op.create_index(
        "ix_encounters_status_started_at", "encounters", ["status", "started_at"], unique=False
    )
    op.create_index(
        "uq_encounters_appointment_live",
        "encounters",
        ["appointment_id"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND appointment_id IS NOT NULL AND status NOT IN ('COMPLETED', 'CANCELLED', 'NO_SHOW', 'REFERRED_OUT', 'LAMA', 'DECEASED')"
        ),
    )
    op.create_index(
        "uq_encounters_number_live",
        "encounters",
        ["hospital_id", "encounter_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "clinical_notes",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "note_type",
            sa.Enum(
                "CHIEF_COMPLAINT",
                "HISTORY",
                "EXAMINATION",
                "ASSESSMENT",
                "PLAN",
                "ADVICE",
                "PROGRESS",
                "NURSING",
                name="notetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("authored_by_id", sa.Uuid(), nullable=False),
        sa.Column("author_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("amends_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["clinical_notes.id"],
            name=op.f("fk_clinical_notes_amends_id_clinical_notes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["authored_by_id"],
            ["users.id"],
            name=op.f("fk_clinical_notes_authored_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_clinical_notes_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_clinical_notes_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_clinical_notes_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["note_templates.id"],
            name=op.f("fk_clinical_notes_template_id_note_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_notes")),
    )
    op.create_index(
        op.f("ix_clinical_notes_amends_id"), "clinical_notes", ["amends_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_authored_by_id"), "clinical_notes", ["authored_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_deleted_at"), "clinical_notes", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_encounter_id"), "clinical_notes", ["encounter_id"], unique=False
    )
    op.create_index(
        "ix_clinical_notes_encounter_id_note_type",
        "clinical_notes",
        ["encounter_id", "note_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_notes_hospital_id"), "clinical_notes", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_is_signed"), "clinical_notes", ["is_signed"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_note_type"), "clinical_notes", ["note_type"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_notes_patient_id"), "clinical_notes", ["patient_id"], unique=False
    )
    op.create_table(
        "diagnoses",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("code_system", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column(
            "diagnosis_type",
            sa.Enum("PROVISIONAL", "DIFFERENTIAL", "FINAL", name="diagnosistype"),
            nullable=False,
        ),
        sa.Column(
            "certainty",
            sa.Enum("SUSPECTED", "PROBABLE", "CONFIRMED", "RULED_OUT", name="diagnosiscertainty"),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("diagnosed_by_id", sa.Uuid(), nullable=False),
        sa.Column("diagnosed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["diagnosed_by_id"],
            ["users.id"],
            name=op.f("fk_diagnoses_diagnosed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_diagnoses_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_diagnoses_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_diagnoses_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
    )
    op.create_index(op.f("ix_diagnoses_code"), "diagnoses", ["code"], unique=False)
    op.create_index(op.f("ix_diagnoses_deleted_at"), "diagnoses", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_diagnoses_diagnosed_by_id"), "diagnoses", ["diagnosed_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnoses_diagnosis_type"), "diagnoses", ["diagnosis_type"], unique=False
    )
    op.create_index(op.f("ix_diagnoses_encounter_id"), "diagnoses", ["encounter_id"], unique=False)
    op.create_index(
        "ix_diagnoses_encounter_id_is_primary",
        "diagnoses",
        ["encounter_id", "is_primary"],
        unique=False,
    )
    op.create_index(op.f("ix_diagnoses_hospital_id"), "diagnoses", ["hospital_id"], unique=False)
    op.create_index(
        "ix_diagnoses_hospital_id_code", "diagnoses", ["hospital_id", "code"], unique=False
    )
    op.create_index(op.f("ix_diagnoses_is_primary"), "diagnoses", ["is_primary"], unique=False)
    op.create_index(op.f("ix_diagnoses_patient_id"), "diagnoses", ["patient_id"], unique=False)
    op.create_table(
        "encounter_events",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "REGISTERED",
                "IN_CONSULTATION",
                "AWAITING_RESULTS",
                "PENDING_CLEARANCE",
                "ADMITTED",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                "REFERRED_OUT",
                "LAMA",
                "DECEASED",
                name="encounterstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "REGISTERED",
                "IN_CONSULTATION",
                "AWAITING_RESULTS",
                "PENDING_CLEARANCE",
                "ADMITTED",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                "REFERRED_OUT",
                "LAMA",
                "DECEASED",
                name="encounterstatus",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_encounter_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_encounter_events_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_encounter_events_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_encounter_events_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_encounter_events")),
    )
    op.create_index(
        op.f("ix_encounter_events_deleted_at"), "encounter_events", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_events_encounter_id"), "encounter_events", ["encounter_id"], unique=False
    )
    op.create_index(
        "ix_encounter_events_encounter_id_occurred_at",
        "encounter_events",
        ["encounter_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_encounter_events_from_status"), "encounter_events", ["from_status"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_events_hospital_id"), "encounter_events", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_events_occurred_at"), "encounter_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_events_patient_id"), "encounter_events", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_encounter_events_to_status"), "encounter_events", ["to_status"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("LAB", "RADIOLOGY", "PHARMACY", "PROCEDURE", "REFERRAL", name="ordertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("REQUESTED", "IN_PROGRESS", "COMPLETED", "CANCELLED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("ROUTINE", "URGENT", "STAT", name="orderpriority"), nullable=False
        ),
        sa.Column("item_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("item_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("review_in_visit", sa.Boolean(), nullable=False),
        sa.Column("blocks_closure", sa.Boolean(), nullable=False),
        sa.Column("ordered_by_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("fulfilment_ref", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_by_id"],
            ["users.id"],
            name=op.f("fk_orders_completed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_orders_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_orders_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ordered_by_id"],
            ["users.id"],
            name=op.f("fk_orders_ordered_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_orders_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_blocks_closure"), "orders", ["blocks_closure"], unique=False)
    op.create_index(op.f("ix_orders_deleted_at"), "orders", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_orders_encounter_id"), "orders", ["encounter_id"], unique=False)
    op.create_index(
        "ix_orders_encounter_id_status", "orders", ["encounter_id", "status"], unique=False
    )
    op.create_index(op.f("ix_orders_hospital_id"), "orders", ["hospital_id"], unique=False)
    op.create_index(
        "ix_orders_hospital_id_order_type_status",
        "orders",
        ["hospital_id", "order_type", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_item_code"), "orders", ["item_code"], unique=False)
    op.create_index(op.f("ix_orders_order_type"), "orders", ["order_type"], unique=False)
    op.create_index(op.f("ix_orders_ordered_at"), "orders", ["ordered_at"], unique=False)
    op.create_index(op.f("ix_orders_ordered_by_id"), "orders", ["ordered_by_id"], unique=False)
    op.create_index(op.f("ix_orders_patient_id"), "orders", ["patient_id"], unique=False)
    op.create_index(op.f("ix_orders_priority"), "orders", ["priority"], unique=False)
    op.create_index(op.f("ix_orders_review_in_visit"), "orders", ["review_in_visit"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "vitals",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("pulse_bpm", sa.Integer(), nullable=True),
        sa.Column("respiratory_rate", sa.Integer(), nullable=True),
        sa.Column("systolic_bp", sa.Integer(), nullable=True),
        sa.Column("diastolic_bp", sa.Integer(), nullable=True),
        sa.Column("spo2_percent", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("bmi", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("pain_score", sa.Integer(), nullable=True),
        sa.Column("blood_glucose_mgdl", sa.Integer(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_abnormal", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_vitals_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_vitals_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_vitals_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_vitals_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vitals")),
    )
    op.create_index(op.f("ix_vitals_deleted_at"), "vitals", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_vitals_encounter_id"), "vitals", ["encounter_id"], unique=False)
    op.create_index(
        "ix_vitals_encounter_id_recorded_at",
        "vitals",
        ["encounter_id", "recorded_at"],
        unique=False,
    )
    op.create_index(op.f("ix_vitals_hospital_id"), "vitals", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_vitals_is_abnormal"), "vitals", ["is_abnormal"], unique=False)
    op.create_index(op.f("ix_vitals_patient_id"), "vitals", ["patient_id"], unique=False)
    op.create_index(op.f("ix_vitals_recorded_at"), "vitals", ["recorded_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vitals_recorded_at"), table_name="vitals")
    op.drop_index(op.f("ix_vitals_patient_id"), table_name="vitals")
    op.drop_index(op.f("ix_vitals_is_abnormal"), table_name="vitals")
    op.drop_index(op.f("ix_vitals_hospital_id"), table_name="vitals")
    op.drop_index("ix_vitals_encounter_id_recorded_at", table_name="vitals")
    op.drop_index(op.f("ix_vitals_encounter_id"), table_name="vitals")
    op.drop_index(op.f("ix_vitals_deleted_at"), table_name="vitals")
    op.drop_table("vitals")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_review_in_visit"), table_name="orders")
    op.drop_index(op.f("ix_orders_priority"), table_name="orders")
    op.drop_index(op.f("ix_orders_patient_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_ordered_by_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_ordered_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_type"), table_name="orders")
    op.drop_index(op.f("ix_orders_item_code"), table_name="orders")
    op.drop_index("ix_orders_hospital_id_order_type_status", table_name="orders")
    op.drop_index(op.f("ix_orders_hospital_id"), table_name="orders")
    op.drop_index("ix_orders_encounter_id_status", table_name="orders")
    op.drop_index(op.f("ix_orders_encounter_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_deleted_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_blocks_closure"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_encounter_events_to_status"), table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_patient_id"), table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_occurred_at"), table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_hospital_id"), table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_from_status"), table_name="encounter_events")
    op.drop_index("ix_encounter_events_encounter_id_occurred_at", table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_encounter_id"), table_name="encounter_events")
    op.drop_index(op.f("ix_encounter_events_deleted_at"), table_name="encounter_events")
    op.drop_table("encounter_events")
    op.drop_index(op.f("ix_diagnoses_patient_id"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_is_primary"), table_name="diagnoses")
    op.drop_index("ix_diagnoses_hospital_id_code", table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_hospital_id"), table_name="diagnoses")
    op.drop_index("ix_diagnoses_encounter_id_is_primary", table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_encounter_id"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_diagnosis_type"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_diagnosed_by_id"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_deleted_at"), table_name="diagnoses")
    op.drop_index(op.f("ix_diagnoses_code"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index(op.f("ix_clinical_notes_patient_id"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_note_type"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_is_signed"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_hospital_id"), table_name="clinical_notes")
    op.drop_index("ix_clinical_notes_encounter_id_note_type", table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_encounter_id"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_deleted_at"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_authored_by_id"), table_name="clinical_notes")
    op.drop_index(op.f("ix_clinical_notes_amends_id"), table_name="clinical_notes")
    op.drop_table("clinical_notes")
    op.drop_index(
        "uq_encounters_number_live",
        table_name="encounters",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_encounters_appointment_live",
        table_name="encounters",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND appointment_id IS NOT NULL AND status NOT IN ('COMPLETED', 'CANCELLED', 'NO_SHOW', 'REFERRED_OUT', 'LAMA', 'DECEASED')"
        ),
    )
    op.drop_index("ix_encounters_status_started_at", table_name="encounters")
    op.drop_index(op.f("ix_encounters_status"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_started_at"), table_name="encounters")
    op.drop_index("ix_encounters_patient_id_started_at", table_name="encounters")
    op.drop_index(op.f("ix_encounters_patient_id"), table_name="encounters")
    op.drop_index("ix_encounters_hospital_id_status", table_name="encounters")
    op.drop_index(op.f("ix_encounters_hospital_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_follow_up_date"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_encounter_type"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_encounter_number"), table_name="encounters")
    op.drop_index("ix_encounters_doctor_id_status", table_name="encounters")
    op.drop_index(op.f("ix_encounters_doctor_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_department_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_deleted_at"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_appointment_id"), table_name="encounters")
    op.drop_table("encounters")
    op.drop_index(op.f("ix_note_templates_title"), table_name="note_templates")
    op.drop_index(op.f("ix_note_templates_template_type"), table_name="note_templates")
    op.drop_index("ix_note_templates_owner_id_is_active", table_name="note_templates")
    op.drop_index(op.f("ix_note_templates_is_active"), table_name="note_templates")
    op.drop_index("ix_note_templates_hospital_id_template_type", table_name="note_templates")
    op.drop_index(op.f("ix_note_templates_hospital_id"), table_name="note_templates")
    op.drop_index(op.f("ix_note_templates_deleted_at"), table_name="note_templates")
    op.drop_table("note_templates")
    op.drop_index("uq_encounter_sequences_hospital_year", table_name="encounter_sequences")
    op.drop_index(op.f("ix_encounter_sequences_year"), table_name="encounter_sequences")
    op.drop_index(op.f("ix_encounter_sequences_hospital_id"), table_name="encounter_sequences")
    op.drop_table("encounter_sequences")
    # ### end Alembic commands ###

    # Alembic drops tables but never the enum types they created, so a
    # downgrade/upgrade cycle otherwise fails with "type already exists".
    # Learned the hard way in the scheduling migration.
    for enum_name in (
        "encounterstatus",
        "encountertype",
        "notetype",
        "templatetype",
        "diagnosistype",
        "diagnosiscertainty",
        "ordertype",
        "orderstatus",
        "orderpriority",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
