"""notifications schema

Revision ID: 374aadf21718
Revises: 9b2ed4471a58
Create Date: 2026-08-11 18:39:12.808607+00:00

Templates, the message record, its per-channel delivery attempts, and the
suppression list that enforces CLAUDE.md §14.

Two indexes here are doing real work rather than optimising a read:

* `uq_notifications_source_live` makes message capture **idempotent** on
  (source module, source type, source id, template code), the same pattern
  `charges` uses. A re-delivered event or a double-click cannot message the same
  patient twice about one report. Terminal-but-unsent statuses are excluded so a
  cancelled or suppressed message can legitimately be raised again later — a
  lifted opt-out, a re-issued report.
* `uq_notification_suppressions_live` keeps one live block per
  (patient, reason, channel, category), and being partial on `lifted_at` means
  lifting one releases the slot for a future re-block.

Row-level security, the permission seed, the default template copy, and the
deceased-patient trigger land in the migration that follows, on the pattern the
earlier module migrations set.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "374aadf21718"
down_revision: str | None = "9b2ed4471a58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "EMAIL", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "APPOINTMENT",
                "REPORT",
                "BILLING",
                "FOLLOW_UP",
                "CRITICAL_ALERT",
                "ADMINISTRATIVE",
                name="notificationcategory",
            ),
            nullable=False,
        ),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_notification_templates_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_templates")),
    )
    op.create_index(
        op.f("ix_notification_templates_category"),
        "notification_templates",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_channel"),
        "notification_templates",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_code"), "notification_templates", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_notification_templates_deleted_at"),
        "notification_templates",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_hospital_id"),
        "notification_templates",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_templates_hospital_id_code",
        "notification_templates",
        ["hospital_id", "code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_is_active"),
        "notification_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_templates_language"),
        "notification_templates",
        ["language"],
        unique=False,
    )
    op.create_index(
        "uq_notification_templates_code_live",
        "notification_templates",
        ["hospital_id", "code", "channel", "language"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "notification_suppressions",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "DECEASED",
                "OPTED_OUT",
                "INVALID_CONTACT",
                "STAFF_BLOCK",
                "DISABLED",
                name="suppressionreason",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "EMAIL", name="notificationchannel"),
            nullable=True,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "APPOINTMENT",
                "REPORT",
                "BILLING",
                "FOLLOW_UP",
                "CRITICAL_ALERT",
                "ADMINISTRATIVE",
                name="notificationcategory",
            ),
            nullable=True,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("lifted_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_notification_suppressions_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by_id"],
            ["users.id"],
            name=op.f("fk_notification_suppressions_lifted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_notification_suppressions_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_notification_suppressions_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_suppressions")),
    )
    op.create_index(
        op.f("ix_notification_suppressions_deleted_at"),
        "notification_suppressions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_suppressions_hospital_id"),
        "notification_suppressions",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_suppressions_lifted_at"),
        "notification_suppressions",
        ["lifted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_suppressions_patient_id"),
        "notification_suppressions",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_suppressions_patient_id_lifted_at",
        "notification_suppressions",
        ["patient_id", "lifted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_suppressions_reason"),
        "notification_suppressions",
        ["reason"],
        unique=False,
    )
    op.create_index(
        "uq_notification_suppressions_live",
        "notification_suppressions",
        ["hospital_id", "patient_id", "reason", "channel", "category"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND lifted_at IS NULL"),
    )
    op.create_table(
        "notifications",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "APPOINTMENT",
                "REPORT",
                "BILLING",
                "FOLLOW_UP",
                "CRITICAL_ALERT",
                "ADMINISTRATIVE",
                name="notificationcategory",
            ),
            nullable=False,
        ),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column(
            "recipient_type", sa.Enum("PATIENT", "STAFF", name="recipienttype"), nullable=False
        ),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("recipient_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("recipient_phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("recipient_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "DELIVERED",
                "FAILED",
                "SUPPRESSED",
                "CANCELLED",
                name="notificationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "EMAIL", name="notificationchannel"),
            nullable=True,
        ),
        sa.Column(
            "restricted_channel",
            sa.Enum("WHATSAPP", "SMS", "EMAIL", name="notificationchannel"),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("dispatch_rounds", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "suppression_reason",
            sa.Enum(
                "DECEASED",
                "OPTED_OUT",
                "INVALID_CONTACT",
                "STAFF_BLOCK",
                "DISABLED",
                name="suppressionreason",
            ),
            nullable=True,
        ),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("needs_template", sa.Boolean(), nullable=False),
        sa.Column("body_is_custom", sa.Boolean(), nullable=False),
        sa.Column("source_module", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("triggered_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_notifications_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_notifications_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_notifications_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_id"],
            ["users.id"],
            name=op.f("fk_notifications_triggered_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_category"), "notifications", ["category"], unique=False)
    op.create_index(op.f("ix_notifications_channel"), "notifications", ["channel"], unique=False)
    op.create_index(
        op.f("ix_notifications_deleted_at"), "notifications", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_encounter_id"), "notifications", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_hospital_id"), "notifications", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_notifications_hospital_id_status",
        "notifications",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_needs_template"), "notifications", ["needs_template"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_patient_id"), "notifications", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_notifications_patient_id_created_at",
        "notifications",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_recipient_type"), "notifications", ["recipient_type"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_source_id"), "notifications", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_source_module"), "notifications", ["source_module"], unique=False
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"], unique=False)
    op.create_index(
        op.f("ix_notifications_suppression_reason"),
        "notifications",
        ["suppression_reason"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_template_code"), "notifications", ["template_code"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        "uq_notifications_source_live",
        "notifications",
        ["hospital_id", "source_module", "source_type", "source_id", "template_code"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND source_id IS NOT NULL AND status NOT IN ('CANCELLED', 'SUPPRESSED', 'FAILED')"
        ),
    )
    op.create_table(
        "notification_attempts",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("WHATSAPP", "SMS", "EMAIL", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("gateway", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column(
            "provider_message_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("error_detail", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_notification_attempts_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_attempts_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_attempts")),
    )
    op.create_index(
        op.f("ix_notification_attempts_channel"), "notification_attempts", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_notification_attempts_hospital_id"),
        "notification_attempts",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_attempts_notification_id"),
        "notification_attempts",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_attempts_notification_id_attempt",
        "notification_attempts",
        ["notification_id", "attempt"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_attempts_succeeded"),
        "notification_attempts",
        ["succeeded"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_attempts_succeeded"), table_name="notification_attempts")
    op.drop_index(
        "ix_notification_attempts_notification_id_attempt", table_name="notification_attempts"
    )
    op.drop_index(
        op.f("ix_notification_attempts_notification_id"), table_name="notification_attempts"
    )
    op.drop_index(op.f("ix_notification_attempts_hospital_id"), table_name="notification_attempts")
    op.drop_index(op.f("ix_notification_attempts_channel"), table_name="notification_attempts")
    op.drop_table("notification_attempts")
    op.drop_index(
        "uq_notifications_source_live",
        table_name="notifications",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND source_id IS NOT NULL AND status NOT IN ('CANCELLED', 'SUPPRESSED', 'FAILED')"
        ),
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_template_code"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_suppression_reason"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_source_module"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_source_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_recipient_type"), table_name="notifications")
    op.drop_index("ix_notifications_patient_id_created_at", table_name="notifications")
    op.drop_index(op.f("ix_notifications_patient_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_needs_template"), table_name="notifications")
    op.drop_index("ix_notifications_hospital_id_status", table_name="notifications")
    op.drop_index(op.f("ix_notifications_hospital_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_encounter_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_deleted_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_channel"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "uq_notification_suppressions_live",
        table_name="notification_suppressions",
        postgresql_where=sa.text("deleted_at IS NULL AND lifted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_notification_suppressions_reason"), table_name="notification_suppressions"
    )
    op.drop_index(
        "ix_notification_suppressions_patient_id_lifted_at", table_name="notification_suppressions"
    )
    op.drop_index(
        op.f("ix_notification_suppressions_patient_id"), table_name="notification_suppressions"
    )
    op.drop_index(
        op.f("ix_notification_suppressions_lifted_at"), table_name="notification_suppressions"
    )
    op.drop_index(
        op.f("ix_notification_suppressions_hospital_id"), table_name="notification_suppressions"
    )
    op.drop_index(
        op.f("ix_notification_suppressions_deleted_at"), table_name="notification_suppressions"
    )
    op.drop_table("notification_suppressions")
    op.drop_index(
        "uq_notification_templates_code_live",
        table_name="notification_templates",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_notification_templates_language"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_is_active"), table_name="notification_templates")
    op.drop_index("ix_notification_templates_hospital_id_code", table_name="notification_templates")
    op.drop_index(
        op.f("ix_notification_templates_hospital_id"), table_name="notification_templates"
    )
    op.drop_index(op.f("ix_notification_templates_deleted_at"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_code"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_channel"), table_name="notification_templates")
    op.drop_index(op.f("ix_notification_templates_category"), table_name="notification_templates")
    op.drop_table("notification_templates")
    # ### end Alembic commands ###

    # Alembic drops tables but never the enum types they created, so a
    # downgrade/upgrade cycle otherwise fails with "type already exists".
    for enum_name in (
        "notificationstatus",
        "notificationcategory",
        "notificationchannel",
        "recipienttype",
        "suppressionreason",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
