"""patients schema

Revision ID: 73970796b94b
Revises: 5e46114656c0
Create Date: 2026-08-03 20:03:25.471222+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "73970796b94b"
down_revision: str | None = "5e46114656c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("uhid", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("name_normalized", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", "UNKNOWN", name="gender"), nullable=False
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("birth_date_is_estimated", sa.Boolean(), nullable=False),
        sa.Column("alternate_phone", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "blood_group",
            sa.Enum(
                "A_POS",
                "A_NEG",
                "B_POS",
                "B_NEG",
                "AB_POS",
                "AB_NEG",
                "O_POS",
                "O_NEG",
                "UNKNOWN",
                name="bloodgroup",
            ),
            nullable=False,
        ),
        sa.Column("marital_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("occupation", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("guardian_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("guardian_relation", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("guardian_phone", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
        sa.Column("address_line1", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("address_line2", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("district", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("pincode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("abha_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("abha_address", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("abha_linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preferred_language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deceased", sa.Boolean(), nullable=False),
        sa.Column("deceased_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_patients_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["patients.id"],
            name=op.f("fk_patients_merged_into_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(op.f("ix_patients_abha_id"), "patients", ["abha_id"], unique=False)
    op.create_index(
        op.f("ix_patients_alternate_phone"), "patients", ["alternate_phone"], unique=False
    )
    op.create_index(op.f("ix_patients_deleted_at"), "patients", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_patients_gender"), "patients", ["gender"], unique=False)
    op.create_index(
        op.f("ix_patients_guardian_phone"), "patients", ["guardian_phone"], unique=False
    )
    op.create_index(op.f("ix_patients_hospital_id"), "patients", ["hospital_id"], unique=False)
    op.create_index(
        "ix_patients_hospital_id_name_normalized",
        "patients",
        ["hospital_id", "name_normalized"],
        unique=False,
    )
    op.create_index(
        "ix_patients_hospital_id_phone", "patients", ["hospital_id", "phone"], unique=False
    )
    op.create_index(op.f("ix_patients_is_active"), "patients", ["is_active"], unique=False)
    op.create_index(op.f("ix_patients_is_deceased"), "patients", ["is_deceased"], unique=False)
    op.create_index(
        op.f("ix_patients_merged_into_id"), "patients", ["merged_into_id"], unique=False
    )
    op.create_index(
        op.f("ix_patients_name_normalized"), "patients", ["name_normalized"], unique=False
    )
    op.create_index(op.f("ix_patients_phone"), "patients", ["phone"], unique=False)
    op.create_index(op.f("ix_patients_pincode"), "patients", ["pincode"], unique=False)
    op.create_index(op.f("ix_patients_uhid"), "patients", ["uhid"], unique=False)
    op.create_index(
        "uq_patients_name_phone_live",
        "patients",
        ["hospital_id", "name_normalized", "phone"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND merged_into_id IS NULL"),
    )
    op.create_index(
        "uq_patients_uhid_live",
        "patients",
        ["hospital_id", "uhid"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "uhid_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_uhid_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uhid_sequences")),
    )
    op.create_index(
        op.f("ix_uhid_sequences_hospital_id"), "uhid_sequences", ["hospital_id"], unique=False
    )
    op.create_index(op.f("ix_uhid_sequences_year"), "uhid_sequences", ["year"], unique=False)
    op.create_index(
        "uq_uhid_sequences_hospital_year", "uhid_sequences", ["hospital_id", "year"], unique=True
    )
    op.create_table(
        "patient_alerts",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "alert_type",
            sa.Enum(
                "DRUG_ALLERGY",
                "FOOD_ALLERGY",
                "HIGH_RISK_CONDITION",
                "INFECTIOUS_PRECAUTION",
                "FALL_RISK",
                "IMPLANT_DEVICE",
                "OTHER",
                name="alerttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MODERATE", "INFO", name="alertseverity"),
            nullable=False,
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_patient_alerts_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_patient_alerts_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_patient_alerts_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_alerts")),
    )
    op.create_index(
        op.f("ix_patient_alerts_alert_type"), "patient_alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_patient_alerts_deleted_at"), "patient_alerts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_patient_alerts_hospital_id"), "patient_alerts", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_patient_alerts_is_active"), "patient_alerts", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_patient_alerts_patient_id"), "patient_alerts", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_patient_alerts_patient_id_is_active",
        "patient_alerts",
        ["patient_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_alerts_severity"), "patient_alerts", ["severity"], unique=False
    )
    op.create_table(
        "patient_consents",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "consent_type",
            sa.Enum(
                "TREATMENT",
                "DATA_PROCESSING",
                "DATA_SHARING",
                "ABHA_LINKAGE",
                "RESEARCH",
                "MARKETING",
                name="consenttype",
            ),
            nullable=False,
        ),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("method", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("given_by", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("given_by_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("given_by_relation", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("document_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_patient_consents_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_patient_consents_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_patient_consents_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_consents")),
    )
    op.create_index(
        op.f("ix_patient_consents_consent_type"), "patient_consents", ["consent_type"], unique=False
    )
    op.create_index(
        op.f("ix_patient_consents_hospital_id"), "patient_consents", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_patient_consents_patient_id"), "patient_consents", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_patient_consents_patient_id_consent_type",
        "patient_consents",
        ["patient_id", "consent_type"],
        unique=False,
    )
    op.create_table(
        "patient_identifiers",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("identifier_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("identifier_value", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("issued_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_patient_identifiers_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_patient_identifiers_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_identifiers")),
    )
    op.create_index(
        op.f("ix_patient_identifiers_deleted_at"),
        "patient_identifiers",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_hospital_id"),
        "patient_identifiers",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_identifier_type"),
        "patient_identifiers",
        ["identifier_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_identifier_value"),
        "patient_identifiers",
        ["identifier_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patient_identifiers_patient_id"),
        "patient_identifiers",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        "uq_patient_identifiers_type_value",
        "patient_identifiers",
        ["hospital_id", "identifier_type", "identifier_value"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_patient_identifiers_type_value",
        table_name="patient_identifiers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_patient_identifiers_patient_id"), table_name="patient_identifiers")
    op.drop_index(op.f("ix_patient_identifiers_identifier_value"), table_name="patient_identifiers")
    op.drop_index(op.f("ix_patient_identifiers_identifier_type"), table_name="patient_identifiers")
    op.drop_index(op.f("ix_patient_identifiers_hospital_id"), table_name="patient_identifiers")
    op.drop_index(op.f("ix_patient_identifiers_deleted_at"), table_name="patient_identifiers")
    op.drop_table("patient_identifiers")
    op.drop_index("ix_patient_consents_patient_id_consent_type", table_name="patient_consents")
    op.drop_index(op.f("ix_patient_consents_patient_id"), table_name="patient_consents")
    op.drop_index(op.f("ix_patient_consents_hospital_id"), table_name="patient_consents")
    op.drop_index(op.f("ix_patient_consents_consent_type"), table_name="patient_consents")
    op.drop_table("patient_consents")
    op.drop_index(op.f("ix_patient_alerts_severity"), table_name="patient_alerts")
    op.drop_index("ix_patient_alerts_patient_id_is_active", table_name="patient_alerts")
    op.drop_index(op.f("ix_patient_alerts_patient_id"), table_name="patient_alerts")
    op.drop_index(op.f("ix_patient_alerts_is_active"), table_name="patient_alerts")
    op.drop_index(op.f("ix_patient_alerts_hospital_id"), table_name="patient_alerts")
    op.drop_index(op.f("ix_patient_alerts_deleted_at"), table_name="patient_alerts")
    op.drop_index(op.f("ix_patient_alerts_alert_type"), table_name="patient_alerts")
    op.drop_table("patient_alerts")
    op.drop_index("uq_uhid_sequences_hospital_year", table_name="uhid_sequences")
    op.drop_index(op.f("ix_uhid_sequences_year"), table_name="uhid_sequences")
    op.drop_index(op.f("ix_uhid_sequences_hospital_id"), table_name="uhid_sequences")
    op.drop_table("uhid_sequences")
    op.drop_index(
        "uq_patients_uhid_live",
        table_name="patients",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_patients_name_phone_live",
        table_name="patients",
        postgresql_where=sa.text("deleted_at IS NULL AND merged_into_id IS NULL"),
    )
    op.drop_index(op.f("ix_patients_uhid"), table_name="patients")
    op.drop_index(op.f("ix_patients_pincode"), table_name="patients")
    op.drop_index(op.f("ix_patients_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_name_normalized"), table_name="patients")
    op.drop_index(op.f("ix_patients_merged_into_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_is_deceased"), table_name="patients")
    op.drop_index(op.f("ix_patients_is_active"), table_name="patients")
    op.drop_index("ix_patients_hospital_id_phone", table_name="patients")
    op.drop_index("ix_patients_hospital_id_name_normalized", table_name="patients")
    op.drop_index(op.f("ix_patients_hospital_id"), table_name="patients")
    op.drop_index(op.f("ix_patients_guardian_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_gender"), table_name="patients")
    op.drop_index(op.f("ix_patients_deleted_at"), table_name="patients")
    op.drop_index(op.f("ix_patients_alternate_phone"), table_name="patients")
    op.drop_index(op.f("ix_patients_abha_id"), table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
