"""billing schema

Revision ID: 2e6914300484
Revises: d81a4b6f5c37
Create Date: 2026-08-08 22:10:00.000000+00:00

Rate cards and their per-service prices, the charge ledger, invoices, payments
and insurance claims.

Two indexes here are doing real work rather than tuning:

* `uq_charges_source_live` makes charge capture idempotent. One live charge per
  (module, type, source act), so a re-delivered event or a double-click cannot
  bill a patient twice for one blood test. Cancelled charges are excluded so a
  cancelled-then-reordered test can be charged again.
* `uq_invoices_encounter_draft` allows one draft per visit, so two staff members
  cannot each assemble half a bill. Issued invoices are excluded — a long stay
  may legitimately produce several.

`invoice_sequences` keys on the **financial** year rather than the calendar
year, unlike every other counter in this system. Rule 46 of the CGST Rules wants
a serial number consecutive and unique for a financial year, and India's runs
April to March.

Row-level security and this module's permission seed land in the migration that
follows, on the pattern the earlier module migrations set.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "2e6914300484"
down_revision: str | None = "d81a4b6f5c37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("financial_year", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_invoice_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_sequences")),
    )
    op.create_index(
        op.f("ix_invoice_sequences_financial_year"),
        "invoice_sequences",
        ["financial_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_sequences_hospital_id"), "invoice_sequences", ["hospital_id"], unique=False
    )
    op.create_index(
        "uq_invoice_sequences_hospital_fy_kind",
        "invoice_sequences",
        ["hospital_id", "financial_year", "kind"],
        unique=True,
    )
    op.create_table(
        "rate_cards",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column(
            "payer_type",
            sa.Enum("CASH", "INSURANCE", "SCHEME", "CORPORATE", name="payertype"),
            nullable=False,
        ),
        sa.Column("scheme_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_rate_cards_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_cards")),
    )
    op.create_index(op.f("ix_rate_cards_code"), "rate_cards", ["code"], unique=False)
    op.create_index(op.f("ix_rate_cards_deleted_at"), "rate_cards", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_rate_cards_hospital_id"), "rate_cards", ["hospital_id"], unique=False)
    op.create_index(
        "ix_rate_cards_hospital_id_payer_type",
        "rate_cards",
        ["hospital_id", "payer_type"],
        unique=False,
    )
    op.create_index(op.f("ix_rate_cards_is_active"), "rate_cards", ["is_active"], unique=False)
    op.create_index(op.f("ix_rate_cards_is_default"), "rate_cards", ["is_default"], unique=False)
    op.create_index(op.f("ix_rate_cards_payer_type"), "rate_cards", ["payer_type"], unique=False)
    op.create_index(op.f("ix_rate_cards_scheme_code"), "rate_cards", ["scheme_code"], unique=False)
    op.create_index(
        "uq_rate_cards_code_live",
        "rate_cards",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "service_items",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CONSULTATION",
                "LAB",
                "RADIOLOGY",
                "PROCEDURE",
                "PHARMACY",
                "ROOM",
                "REGISTRATION",
                "OTHER",
                name="chargecategory",
            ),
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("doctor_id", sa.Uuid(), nullable=True),
        sa.Column("is_gst_exempt", sa.Boolean(), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("hsn_sac_code", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_service_items_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_service_items_doctor_id_doctors"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_service_items_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_items")),
    )
    op.create_index(op.f("ix_service_items_category"), "service_items", ["category"], unique=False)
    op.create_index(op.f("ix_service_items_code"), "service_items", ["code"], unique=False)
    op.create_index(
        op.f("ix_service_items_deleted_at"), "service_items", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_service_items_department_id"), "service_items", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_items_doctor_id"), "service_items", ["doctor_id"], unique=False
    )
    op.create_index(
        "ix_service_items_doctor_id_category",
        "service_items",
        ["doctor_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_items_hospital_id"), "service_items", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_service_items_hospital_id_category",
        "service_items",
        ["hospital_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_items_is_active"), "service_items", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_service_items_name"), "service_items", ["name"], unique=False)
    op.create_index(
        "uq_service_items_code_live",
        "service_items",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "service_prices",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_item_id", sa.Uuid(), nullable=False),
        sa.Column("rate_card_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_package", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_service_prices_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_card_id"],
            ["rate_cards.id"],
            name=op.f("fk_service_prices_rate_card_id_rate_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["service_item_id"],
            ["service_items.id"],
            name=op.f("fk_service_prices_service_item_id_service_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_prices")),
    )
    op.create_index(
        op.f("ix_service_prices_deleted_at"), "service_prices", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_service_prices_hospital_id"), "service_prices", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_prices_rate_card_id"), "service_prices", ["rate_card_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_prices_service_item_id"),
        "service_prices",
        ["service_item_id"],
        unique=False,
    )
    op.create_index(
        "uq_service_prices_item_card_live",
        "service_prices",
        ["service_item_id", "rate_card_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "invoices",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("rate_card_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payer_type",
            sa.Enum("CASH", "INSURANCE", "SCHEME", "CORPORATE", name="payertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ISSUED",
                "PARTIALLY_PAID",
                "PAID",
                "CANCELLED",
                "WRITTEN_OFF",
                name="invoicestatus",
            ),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("taxable_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cgst_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sgst_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("igst_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_due", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payer_liability", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("hospital_gstin", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
        sa.Column("place_of_supply", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("is_interstate", sa.Boolean(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_by_id", sa.Uuid(), nullable=True),
        sa.Column("settlement_context", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("settlement_note", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("write_off_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("write_off_by_id", sa.Uuid(), nullable=True),
        sa.Column("credits_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["credits_invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoices_credits_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_invoices_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_invoices_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_id"],
            ["users.id"],
            name=op.f("fk_invoices_issued_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_invoices_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_card_id"],
            ["rate_cards.id"],
            name=op.f("fk_invoices_rate_card_id_rate_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["write_off_by_id"],
            ["users.id"],
            name=op.f("fk_invoices_write_off_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_index(
        op.f("ix_invoices_credits_invoice_id"), "invoices", ["credits_invoice_id"], unique=False
    )
    op.create_index(op.f("ix_invoices_deleted_at"), "invoices", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_invoices_encounter_id"), "invoices", ["encounter_id"], unique=False)
    op.create_index(
        "ix_invoices_encounter_id_status", "invoices", ["encounter_id", "status"], unique=False
    )
    op.create_index(op.f("ix_invoices_hospital_id"), "invoices", ["hospital_id"], unique=False)
    op.create_index(
        "ix_invoices_hospital_id_status", "invoices", ["hospital_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=False
    )
    op.create_index(op.f("ix_invoices_patient_id"), "invoices", ["patient_id"], unique=False)
    op.create_index(
        "ix_invoices_patient_id_created_at", "invoices", ["patient_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_invoices_payer_type"), "invoices", ["payer_type"], unique=False)
    op.create_index(op.f("ix_invoices_rate_card_id"), "invoices", ["rate_card_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_settlement_context"), "invoices", ["settlement_context"], unique=False
    )
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(
        "uq_invoices_encounter_draft",
        "invoices",
        ["encounter_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'DRAFT'"),
    )
    op.create_index(
        "uq_invoices_number_live",
        "invoices",
        ["hospital_id", "invoice_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "charges",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("source_module", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("service_item_id", sa.Uuid(), nullable=True),
        sa.Column("rate_card_id", sa.Uuid(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "CONSULTATION",
                "LAB",
                "RADIOLOGY",
                "PROCEDURE",
                "PHARMACY",
                "ROOM",
                "REGISTRATION",
                "OTHER",
                name="chargecategory",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=9, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("taxable_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cgst_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sgst_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("igst_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("hsn_sac_code", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "INVOICED", "CANCELLED", "WAIVED", name="chargestatus"),
            nullable=False,
        ),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("needs_pricing", sa.Boolean(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_by_id", sa.Uuid(), nullable=True),
        sa.Column("waived_by_id", sa.Uuid(), nullable=True),
        sa.Column("waiver_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["captured_by_id"],
            ["users.id"],
            name=op.f("fk_charges_captured_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_charges_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_charges_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_charges_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_charges_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_card_id"],
            ["rate_cards.id"],
            name=op.f("fk_charges_rate_card_id_rate_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["service_item_id"],
            ["service_items.id"],
            name=op.f("fk_charges_service_item_id_service_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["waived_by_id"],
            ["users.id"],
            name=op.f("fk_charges_waived_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
    )
    op.create_index(op.f("ix_charges_captured_at"), "charges", ["captured_at"], unique=False)
    op.create_index(op.f("ix_charges_category"), "charges", ["category"], unique=False)
    op.create_index(op.f("ix_charges_deleted_at"), "charges", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_charges_encounter_id"), "charges", ["encounter_id"], unique=False)
    op.create_index(
        "ix_charges_encounter_id_status", "charges", ["encounter_id", "status"], unique=False
    )
    op.create_index(op.f("ix_charges_hospital_id"), "charges", ["hospital_id"], unique=False)
    op.create_index(
        "ix_charges_hospital_id_needs_pricing",
        "charges",
        ["hospital_id", "needs_pricing"],
        unique=False,
    )
    op.create_index("ix_charges_invoice_id", "charges", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_charges_needs_pricing"), "charges", ["needs_pricing"], unique=False)
    op.create_index(op.f("ix_charges_patient_id"), "charges", ["patient_id"], unique=False)
    op.create_index(op.f("ix_charges_rate_card_id"), "charges", ["rate_card_id"], unique=False)
    op.create_index(
        op.f("ix_charges_service_item_id"), "charges", ["service_item_id"], unique=False
    )
    op.create_index(op.f("ix_charges_source_id"), "charges", ["source_id"], unique=False)
    op.create_index(op.f("ix_charges_source_module"), "charges", ["source_module"], unique=False)
    op.create_index(op.f("ix_charges_status"), "charges", ["status"], unique=False)
    op.create_index(
        "uq_charges_source_live",
        "charges",
        ["hospital_id", "source_module", "source_type", "source_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    op.create_table(
        "insurance_claims",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("claim_number", sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("payer_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("scheme_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("policy_number", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("tpa_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "QUERIED",
                "APPROVED",
                "REJECTED",
                "SETTLED",
                name="claimstatus",
            ),
            nullable=False,
        ),
        sa.Column("claimed_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("approved_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("settled_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remarks", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_insurance_claims_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_insurance_claims_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_insurance_claims_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insurance_claims")),
    )
    op.create_index(
        op.f("ix_insurance_claims_claim_number"), "insurance_claims", ["claim_number"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_claims_deleted_at"), "insurance_claims", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_claims_hospital_id"), "insurance_claims", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_insurance_claims_hospital_id_status",
        "insurance_claims",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_claims_invoice_id"), "insurance_claims", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_claims_patient_id"), "insurance_claims", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_claims_scheme_code"), "insurance_claims", ["scheme_code"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_claims_status"), "insurance_claims", ["status"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "UPI",
                "CARD",
                "CASH",
                "NETBANKING",
                "WALLET",
                "CHEQUE",
                "INSURANCE",
                "SCHEME",
                "ADJUSTMENT",
                name="paymentmethod",
            ),
            nullable=False,
        ),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("payer_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("status", sa.Enum("RECORDED", "REVERSED", name="paymentstatus"), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_by_id", sa.Uuid(), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversal_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("reverses_payment_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_payments_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payments_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_payments_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"],
            ["users.id"],
            name=op.f("fk_payments_received_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_payment_id"],
            ["payments.id"],
            name=op.f("fk_payments_reverses_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_deleted_at"), "payments", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_payments_hospital_id"), "payments", ["hospital_id"], unique=False)
    op.create_index(
        "ix_payments_hospital_id_received_at",
        "payments",
        ["hospital_id", "received_at"],
        unique=False,
    )
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_index(
        "ix_payments_invoice_id_status", "payments", ["invoice_id", "status"], unique=False
    )
    op.create_index(op.f("ix_payments_method"), "payments", ["method"], unique=False)
    op.create_index(op.f("ix_payments_patient_id"), "payments", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_payments_receipt_number"), "payments", ["receipt_number"], unique=False
    )
    op.create_index(op.f("ix_payments_received_at"), "payments", ["received_at"], unique=False)
    op.create_index(op.f("ix_payments_reference"), "payments", ["reference"], unique=False)
    op.create_index(
        op.f("ix_payments_reverses_payment_id"), "payments", ["reverses_payment_id"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(
        "uq_payments_receipt_live",
        "payments",
        ["hospital_id", "receipt_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payments_receipt_live",
        table_name="payments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_reverses_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_reference"), table_name="payments")
    op.drop_index(op.f("ix_payments_received_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_receipt_number"), table_name="payments")
    op.drop_index(op.f("ix_payments_patient_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_method"), table_name="payments")
    op.drop_index("ix_payments_invoice_id_status", table_name="payments")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index("ix_payments_hospital_id_received_at", table_name="payments")
    op.drop_index(op.f("ix_payments_hospital_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_deleted_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_insurance_claims_status"), table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_scheme_code"), table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_patient_id"), table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_invoice_id"), table_name="insurance_claims")
    op.drop_index("ix_insurance_claims_hospital_id_status", table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_hospital_id"), table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_deleted_at"), table_name="insurance_claims")
    op.drop_index(op.f("ix_insurance_claims_claim_number"), table_name="insurance_claims")
    op.drop_table("insurance_claims")
    op.drop_index(
        "uq_charges_source_live",
        table_name="charges",
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    op.drop_index(op.f("ix_charges_status"), table_name="charges")
    op.drop_index(op.f("ix_charges_source_module"), table_name="charges")
    op.drop_index(op.f("ix_charges_source_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_service_item_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_rate_card_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_patient_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_needs_pricing"), table_name="charges")
    op.drop_index("ix_charges_invoice_id", table_name="charges")
    op.drop_index("ix_charges_hospital_id_needs_pricing", table_name="charges")
    op.drop_index(op.f("ix_charges_hospital_id"), table_name="charges")
    op.drop_index("ix_charges_encounter_id_status", table_name="charges")
    op.drop_index(op.f("ix_charges_encounter_id"), table_name="charges")
    op.drop_index(op.f("ix_charges_deleted_at"), table_name="charges")
    op.drop_index(op.f("ix_charges_category"), table_name="charges")
    op.drop_index(op.f("ix_charges_captured_at"), table_name="charges")
    op.drop_table("charges")
    op.drop_index(
        "uq_invoices_number_live",
        table_name="invoices",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_invoices_encounter_draft",
        table_name="invoices",
        postgresql_where=sa.text("deleted_at IS NULL AND status = 'DRAFT'"),
    )
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_settlement_context"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_rate_card_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_payer_type"), table_name="invoices")
    op.drop_index("ix_invoices_patient_id_created_at", table_name="invoices")
    op.drop_index(op.f("ix_invoices_patient_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index("ix_invoices_hospital_id_status", table_name="invoices")
    op.drop_index(op.f("ix_invoices_hospital_id"), table_name="invoices")
    op.drop_index("ix_invoices_encounter_id_status", table_name="invoices")
    op.drop_index(op.f("ix_invoices_encounter_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_deleted_at"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_credits_invoice_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(
        "uq_service_prices_item_card_live",
        table_name="service_prices",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_service_prices_service_item_id"), table_name="service_prices")
    op.drop_index(op.f("ix_service_prices_rate_card_id"), table_name="service_prices")
    op.drop_index(op.f("ix_service_prices_hospital_id"), table_name="service_prices")
    op.drop_index(op.f("ix_service_prices_deleted_at"), table_name="service_prices")
    op.drop_table("service_prices")
    op.drop_index(
        "uq_service_items_code_live",
        table_name="service_items",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_service_items_name"), table_name="service_items")
    op.drop_index(op.f("ix_service_items_is_active"), table_name="service_items")
    op.drop_index("ix_service_items_hospital_id_category", table_name="service_items")
    op.drop_index(op.f("ix_service_items_hospital_id"), table_name="service_items")
    op.drop_index("ix_service_items_doctor_id_category", table_name="service_items")
    op.drop_index(op.f("ix_service_items_doctor_id"), table_name="service_items")
    op.drop_index(op.f("ix_service_items_department_id"), table_name="service_items")
    op.drop_index(op.f("ix_service_items_deleted_at"), table_name="service_items")
    op.drop_index(op.f("ix_service_items_code"), table_name="service_items")
    op.drop_index(op.f("ix_service_items_category"), table_name="service_items")
    op.drop_table("service_items")
    op.drop_index(
        "uq_rate_cards_code_live",
        table_name="rate_cards",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_rate_cards_scheme_code"), table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_payer_type"), table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_is_default"), table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_is_active"), table_name="rate_cards")
    op.drop_index("ix_rate_cards_hospital_id_payer_type", table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_hospital_id"), table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_deleted_at"), table_name="rate_cards")
    op.drop_index(op.f("ix_rate_cards_code"), table_name="rate_cards")
    op.drop_table("rate_cards")
    op.drop_index("uq_invoice_sequences_hospital_fy_kind", table_name="invoice_sequences")
    op.drop_index(op.f("ix_invoice_sequences_hospital_id"), table_name="invoice_sequences")
    op.drop_index(op.f("ix_invoice_sequences_financial_year"), table_name="invoice_sequences")
    op.drop_table("invoice_sequences")
    # ### end Alembic commands ###

    # Alembic drops tables but never the enum types they created, so a
    # downgrade/upgrade cycle otherwise fails with "type already exists".
    for enum_name in (
        "claimstatus",
        "paymentstatus",
        "paymentmethod",
        "invoicestatus",
        "chargestatus",
        "chargecategory",
        "payertype",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
