"""scheduling schema and departments

Revision ID: c9c90527110f
Revises: 4da6880ebc84
Create Date: 2026-08-03 21:14:53.143568+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "c9c90527110f"
down_revision: str | None = "4da6880ebc84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointment_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_appointment_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointment_sequences")),
    )
    op.create_index(
        op.f("ix_appointment_sequences_hospital_id"),
        "appointment_sequences",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointment_sequences_year"), "appointment_sequences", ["year"], unique=False
    )
    op.create_index(
        "uq_appointment_sequences_hospital_year",
        "appointment_sequences",
        ["hospital_id", "year"],
        unique=True,
    )
    op.create_table(
        "departments",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column(
            "department_type",
            sa.Enum(
                "OPD",
                "IPD",
                "EMERGENCY",
                "DIAGNOSTIC",
                "PHARMACY",
                "SUPPORT",
                name="departmenttype",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("phone_extension", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("head_doctor_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["head_doctor_id"],
            ["users.id"],
            name=op.f("fk_departments_head_doctor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_departments_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=False)
    op.create_index(op.f("ix_departments_deleted_at"), "departments", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_departments_department_type"), "departments", ["department_type"], unique=False
    )
    op.create_index(
        op.f("ix_departments_head_doctor_id"), "departments", ["head_doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_departments_hospital_id"), "departments", ["hospital_id"], unique=False
    )
    op.create_index(op.f("ix_departments_is_active"), "departments", ["is_active"], unique=False)
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=False)
    op.create_index(
        "uq_departments_code_live",
        "departments",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "doctors",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("specialty", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("qualification", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "registration_number", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("default_slot_minutes", sa.Integer(), nullable=False),
        sa.Column("is_accepting_appointments", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_doctors_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_doctors_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_doctors_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctors")),
    )
    op.create_index(op.f("ix_doctors_deleted_at"), "doctors", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_doctors_department_id"), "doctors", ["department_id"], unique=False)
    op.create_index(op.f("ix_doctors_display_name"), "doctors", ["display_name"], unique=False)
    op.create_index(op.f("ix_doctors_hospital_id"), "doctors", ["hospital_id"], unique=False)
    op.create_index(
        "ix_doctors_hospital_id_department_id",
        "doctors",
        ["hospital_id", "department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doctors_is_accepting_appointments"),
        "doctors",
        ["is_accepting_appointments"],
        unique=False,
    )
    op.create_index(op.f("ix_doctors_is_active"), "doctors", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_doctors_registration_number"), "doctors", ["registration_number"], unique=False
    )
    op.create_index(op.f("ix_doctors_specialty"), "doctors", ["specialty"], unique=False)
    op.create_index(op.f("ix_doctors_user_id"), "doctors", ["user_id"], unique=False)
    op.create_index(
        "uq_doctors_user_live",
        "doctors",
        ["hospital_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "appointments",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "appointment_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CHECKED_IN",
                "IN_CONSULTATION",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                "RESCHEDULED",
                name="appointmentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "WALK_IN",
                "PHONE",
                "COUNTER",
                "ONLINE",
                "REFERRAL",
                "FOLLOW_UP",
                name="appointmentsource",
            ),
            nullable=False,
        ),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("booked_by_id", sa.Uuid(), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("cancelled_by_patient", sa.Boolean(), nullable=False),
        sa.Column("no_show_marked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rescheduled_to_id", sa.Uuid(), nullable=True),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booked_by_id"],
            ["users.id"],
            name=op.f("fk_appointments_booked_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_appointments_cancelled_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_appointments_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_appointments_doctor_id_doctors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_appointments_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_appointments_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rescheduled_to_id"],
            ["appointments.id"],
            name=op.f("fk_appointments_rescheduled_to_id_appointments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index(
        op.f("ix_appointments_appointment_number"),
        "appointments",
        ["appointment_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_deleted_at"), "appointments", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_department_id"), "appointments", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_appointments_doctor_id"), "appointments", ["doctor_id"], unique=False)
    op.create_index(
        "ix_appointments_doctor_id_scheduled_start",
        "appointments",
        ["doctor_id", "scheduled_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_encounter_id"), "appointments", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_hospital_id"), "appointments", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_appointments_hospital_id_status",
        "appointments",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_appointments_patient_id_scheduled_start",
        "appointments",
        ["patient_id", "scheduled_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_rescheduled_to_id"),
        "appointments",
        ["rescheduled_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_scheduled_start"), "appointments", ["scheduled_start"], unique=False
    )
    op.create_index(op.f("ix_appointments_source"), "appointments", ["source"], unique=False)
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_index(
        "uq_appointments_doctor_slot_live",
        "appointments",
        ["doctor_id", "scheduled_start"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status NOT IN ('CANCELLED', 'NO_SHOW', 'RESCHEDULED')"
        ),
    )
    op.create_index(
        "uq_appointments_number_live",
        "appointments",
        ["hospital_id", "appointment_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "availability_exceptions",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("slot_minutes", sa.Integer(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("recorded_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_availability_exceptions_doctor_id_doctors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_availability_exceptions_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_availability_exceptions_recorded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_exceptions")),
    )
    op.create_index(
        op.f("ix_availability_exceptions_deleted_at"),
        "availability_exceptions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_exceptions_doctor_id"),
        "availability_exceptions",
        ["doctor_id"],
        unique=False,
    )
    op.create_index(
        "ix_availability_exceptions_doctor_id_date",
        "availability_exceptions",
        ["doctor_id", "exception_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_exceptions_exception_date"),
        "availability_exceptions",
        ["exception_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_availability_exceptions_hospital_id"),
        "availability_exceptions",
        ["hospital_id"],
        unique=False,
    )
    op.create_table(
        "doctor_availabilities",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "weekday",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="weekday",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_doctor_availabilities_doctor_id_doctors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_doctor_availabilities_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_doctor_availabilities")),
    )
    op.create_index(
        op.f("ix_doctor_availabilities_deleted_at"),
        "doctor_availabilities",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doctor_availabilities_doctor_id"),
        "doctor_availabilities",
        ["doctor_id"],
        unique=False,
    )
    op.create_index(
        "ix_doctor_availabilities_doctor_id_weekday",
        "doctor_availabilities",
        ["doctor_id", "weekday"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doctor_availabilities_hospital_id"),
        "doctor_availabilities",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doctor_availabilities_is_active"),
        "doctor_availabilities",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_doctor_availabilities_weekday"), "doctor_availabilities", ["weekday"], unique=False
    )
    op.create_table(
        "token_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("queue_date", sa.Date(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_token_sequences_doctor_id_doctors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_token_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_token_sequences")),
    )
    op.create_index(
        op.f("ix_token_sequences_doctor_id"), "token_sequences", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_sequences_hospital_id"), "token_sequences", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_sequences_queue_date"), "token_sequences", ["queue_date"], unique=False
    )
    op.create_index(
        "uq_token_sequences_doctor_date",
        "token_sequences",
        ["hospital_id", "doctor_id", "queue_date"],
        unique=True,
    )
    op.create_table(
        "queue_entries",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("queue_date", sa.Date(), nullable=False),
        sa.Column("token_number", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "CALLED",
                "IN_CONSULTATION",
                "COMPLETED",
                "SKIPPED",
                "LEFT_WITHOUT_BEING_SEEN",
                name="queuestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("EMERGENCY", "PRIORITY", "NORMAL", name="queuepriority"),
            nullable=False,
        ),
        sa.Column("priority_reason", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skip_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_queue_entries_appointment_id_appointments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_queue_entries_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
            name=op.f("fk_queue_entries_doctor_id_doctors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_queue_entries_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_queue_entries_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_entries")),
    )
    op.create_index(
        op.f("ix_queue_entries_appointment_id"), "queue_entries", ["appointment_id"], unique=False
    )
    op.create_index(
        op.f("ix_queue_entries_deleted_at"), "queue_entries", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_queue_entries_department_id"), "queue_entries", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_queue_entries_doctor_id"), "queue_entries", ["doctor_id"], unique=False
    )
    op.create_index(
        "ix_queue_entries_doctor_id_queue_date_status",
        "queue_entries",
        ["doctor_id", "queue_date", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_queue_entries_hospital_id"), "queue_entries", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_queue_entries_patient_id"), "queue_entries", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_queue_entries_priority"), "queue_entries", ["priority"], unique=False)
    op.create_index(
        op.f("ix_queue_entries_queue_date"), "queue_entries", ["queue_date"], unique=False
    )
    op.create_index(op.f("ix_queue_entries_status"), "queue_entries", ["status"], unique=False)
    op.create_index(
        "uq_queue_entries_token_live",
        "queue_entries",
        ["hospital_id", "doctor_id", "queue_date", "token_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_queue_entries_token_live",
        table_name="queue_entries",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_queue_entries_status"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_queue_date"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_priority"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_patient_id"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_hospital_id"), table_name="queue_entries")
    op.drop_index("ix_queue_entries_doctor_id_queue_date_status", table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_doctor_id"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_department_id"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_deleted_at"), table_name="queue_entries")
    op.drop_index(op.f("ix_queue_entries_appointment_id"), table_name="queue_entries")
    op.drop_table("queue_entries")
    op.drop_index("uq_token_sequences_doctor_date", table_name="token_sequences")
    op.drop_index(op.f("ix_token_sequences_queue_date"), table_name="token_sequences")
    op.drop_index(op.f("ix_token_sequences_hospital_id"), table_name="token_sequences")
    op.drop_index(op.f("ix_token_sequences_doctor_id"), table_name="token_sequences")
    op.drop_table("token_sequences")
    op.drop_index(op.f("ix_doctor_availabilities_weekday"), table_name="doctor_availabilities")
    op.drop_index(op.f("ix_doctor_availabilities_is_active"), table_name="doctor_availabilities")
    op.drop_index(op.f("ix_doctor_availabilities_hospital_id"), table_name="doctor_availabilities")
    op.drop_index("ix_doctor_availabilities_doctor_id_weekday", table_name="doctor_availabilities")
    op.drop_index(op.f("ix_doctor_availabilities_doctor_id"), table_name="doctor_availabilities")
    op.drop_index(op.f("ix_doctor_availabilities_deleted_at"), table_name="doctor_availabilities")
    op.drop_table("doctor_availabilities")
    op.drop_index(
        op.f("ix_availability_exceptions_hospital_id"), table_name="availability_exceptions"
    )
    op.drop_index(
        op.f("ix_availability_exceptions_exception_date"), table_name="availability_exceptions"
    )
    op.drop_index("ix_availability_exceptions_doctor_id_date", table_name="availability_exceptions")
    op.drop_index(
        op.f("ix_availability_exceptions_doctor_id"), table_name="availability_exceptions"
    )
    op.drop_index(
        op.f("ix_availability_exceptions_deleted_at"), table_name="availability_exceptions"
    )
    op.drop_table("availability_exceptions")
    op.drop_index(
        "uq_appointments_number_live",
        table_name="appointments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_appointments_doctor_slot_live",
        table_name="appointments",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status NOT IN ('CANCELLED', 'NO_SHOW', 'RESCHEDULED')"
        ),
    )
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_source"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_scheduled_start"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_rescheduled_to_id"), table_name="appointments")
    op.drop_index("ix_appointments_patient_id_scheduled_start", table_name="appointments")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index("ix_appointments_hospital_id_status", table_name="appointments")
    op.drop_index(op.f("ix_appointments_hospital_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_encounter_id"), table_name="appointments")
    op.drop_index("ix_appointments_doctor_id_scheduled_start", table_name="appointments")
    op.drop_index(op.f("ix_appointments_doctor_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_department_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_deleted_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_appointment_number"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(
        "uq_doctors_user_live", table_name="doctors", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_doctors_user_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_specialty"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_registration_number"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_is_active"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_is_accepting_appointments"), table_name="doctors")
    op.drop_index("ix_doctors_hospital_id_department_id", table_name="doctors")
    op.drop_index(op.f("ix_doctors_hospital_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_display_name"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_department_id"), table_name="doctors")
    op.drop_index(op.f("ix_doctors_deleted_at"), table_name="doctors")
    op.drop_table("doctors")
    op.drop_index(
        "uq_departments_code_live",
        table_name="departments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_is_active"), table_name="departments")
    op.drop_index(op.f("ix_departments_hospital_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_head_doctor_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_department_type"), table_name="departments")
    op.drop_index(op.f("ix_departments_deleted_at"), table_name="departments")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    op.drop_index("uq_appointment_sequences_hospital_year", table_name="appointment_sequences")
    op.drop_index(op.f("ix_appointment_sequences_year"), table_name="appointment_sequences")
    op.drop_index(op.f("ix_appointment_sequences_hospital_id"), table_name="appointment_sequences")
    op.drop_table("appointment_sequences")
    # Alembic drops the tables but leaves their enum types behind, so a
    # downgrade/upgrade cycle would fail with "type already exists". Drop them
    # so this migration is genuinely reversible.
    for enum_name in (
        "queuestatus",
        "queuepriority",
        "appointmentstatus",
        "appointmentsource",
        "weekday",
        "departmenttype",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
