"""ipd schema

Revision ID: 576a17eb0126
Revises: c58d0a3e91b7
Create Date: 2026-08-12 03:38:00.434193+00:00

The inpatient tables: wards and beds, the admission and its bed history, the
medication chart, and the discharge summary. RLS and permissions follow in the
next revision, on the pattern every module here has used.

Four partial unique indexes carry real weight and are worth knowing about before
anybody edits this file, because each one is the last line of defence for a
mistake the application layer is meant to catch first:

* `uq_bed_assignments_bed_live` — one live occupant per bed. Without it, two
  concurrent admissions racing on the same bed both succeed and a patient is
  walked to an occupied room.
* `uq_bed_assignments_admission_live` — one live bed per admission. A patient is
  in one place at a time, and a transfer that half-failed would otherwise leave
  them in two.
* `uq_admissions_encounter_live` — a visit cannot be admitted twice, which is
  what stops one stay producing two bills.
* `uq_medication_administrations_slot` — one dose per order per due time, which
  is what makes the chart materialiser safe to re-run.

All four are partial (`WHERE deleted_at IS NULL AND ...`) so that soft-deleted
and cancelled rows do not block a legitimate re-entry.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "576a17eb0126"
down_revision: str | None = "c58d0a3e91b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admission_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_admission_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_sequences")),
    )
    op.create_index(
        op.f("ix_admission_sequences_hospital_id"),
        "admission_sequences",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admission_sequences_year"), "admission_sequences", ["year"], unique=False
    )
    op.create_index(
        "uq_admission_sequences_hospital_year",
        "admission_sequences",
        ["hospital_id", "year"],
        unique=True,
    )
    op.create_table(
        "wards",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("floor", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "bed_class",
            sa.Enum(
                "GENERAL",
                "SEMI_PRIVATE",
                "PRIVATE",
                "DELUXE",
                "ICU",
                "HDU",
                "NICU",
                "EMERGENCY",
                "DAY_CARE",
                name="bedclass",
            ),
            nullable=False,
        ),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("gender_policy", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("phone_extension", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_wards_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_wards_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wards")),
    )
    op.create_index(op.f("ix_wards_bed_class"), "wards", ["bed_class"], unique=False)
    op.create_index(op.f("ix_wards_code"), "wards", ["code"], unique=False)
    op.create_index(op.f("ix_wards_deleted_at"), "wards", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_wards_department_id"), "wards", ["department_id"], unique=False)
    op.create_index(op.f("ix_wards_hospital_id"), "wards", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_wards_is_active"), "wards", ["is_active"], unique=False)
    op.create_index(op.f("ix_wards_name"), "wards", ["name"], unique=False)
    op.create_index(
        "uq_wards_code_live",
        "wards",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "beds",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ward_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column(
            "bed_class",
            sa.Enum(
                "GENERAL",
                "SEMI_PRIVATE",
                "PRIVATE",
                "DELUXE",
                "ICU",
                "HDU",
                "NICU",
                "EMERGENCY",
                "DAY_CARE",
                name="bedclass",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE", "OCCUPIED", "CLEANING", "RESERVED", "OUT_OF_SERVICE", name="bedstatus"
            ),
            nullable=False,
        ),
        sa.Column("reserved_for_patient_id", sa.Uuid(), nullable=True),
        sa.Column(
            "out_of_service_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tariff_item_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_beds_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reserved_for_patient_id"],
            ["patients.id"],
            name=op.f("fk_beds_reserved_for_patient_id_patients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ward_id"], ["wards.id"], name=op.f("fk_beds_ward_id_wards"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_beds")),
    )
    op.create_index(op.f("ix_beds_bed_class"), "beds", ["bed_class"], unique=False)
    op.create_index(op.f("ix_beds_code"), "beds", ["code"], unique=False)
    op.create_index(op.f("ix_beds_deleted_at"), "beds", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_beds_hospital_id"), "beds", ["hospital_id"], unique=False)
    op.create_index(
        "ix_beds_hospital_id_bed_class_status",
        "beds",
        ["hospital_id", "bed_class", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_beds_is_active"), "beds", ["is_active"], unique=False)
    op.create_index(op.f("ix_beds_status"), "beds", ["status"], unique=False)
    op.create_index(op.f("ix_beds_tariff_item_code"), "beds", ["tariff_item_code"], unique=False)
    op.create_index(op.f("ix_beds_ward_id"), "beds", ["ward_id"], unique=False)
    op.create_index("ix_beds_ward_id_status", "beds", ["ward_id", "status"], unique=False)
    op.create_index(
        "uq_beds_code_live",
        "beds",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "admissions",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admission_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("attending_doctor_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ADMITTED", "DISCHARGE_INITIATED", "DISCHARGED", "CANCELLED", name="admissionstatus"
            ),
            nullable=False,
        ),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provisional_diagnosis", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("admission_notes", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("expected_stay_days", sa.Integer(), nullable=True),
        sa.Column("attendant_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("attendant_phone", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
        sa.Column("attendant_relation", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("discharge_initiated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discharged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discharge_type",
            sa.Enum(
                "RECOVERED", "REFERRED", "LAMA", "DECEASED", "TRANSFERRED_OUT", name="dischargetype"
            ),
            nullable=True,
        ),
        sa.Column("discharged_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("bed_days_charged", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attending_doctor_id"],
            ["doctors.id"],
            name=op.f("fk_admissions_attending_doctor_id_doctors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_admissions_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["discharged_by_id"],
            ["users.id"],
            name=op.f("fk_admissions_discharged_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_admissions_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_admissions_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_admissions_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admissions")),
    )
    op.create_index(
        op.f("ix_admissions_admission_number"), "admissions", ["admission_number"], unique=False
    )
    op.create_index(op.f("ix_admissions_admitted_at"), "admissions", ["admitted_at"], unique=False)
    op.create_index(
        op.f("ix_admissions_attending_doctor_id"),
        "admissions",
        ["attending_doctor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_admissions_deleted_at"), "admissions", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_admissions_department_id"), "admissions", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_admissions_discharge_type"), "admissions", ["discharge_type"], unique=False
    )
    op.create_index(
        op.f("ix_admissions_discharged_at"), "admissions", ["discharged_at"], unique=False
    )
    op.create_index(
        op.f("ix_admissions_encounter_id"), "admissions", ["encounter_id"], unique=False
    )
    op.create_index(op.f("ix_admissions_hospital_id"), "admissions", ["hospital_id"], unique=False)
    op.create_index(
        "ix_admissions_hospital_id_status", "admissions", ["hospital_id", "status"], unique=False
    )
    op.create_index(op.f("ix_admissions_patient_id"), "admissions", ["patient_id"], unique=False)
    op.create_index(
        "ix_admissions_patient_id_admitted_at",
        "admissions",
        ["patient_id", "admitted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_admissions_status"), "admissions", ["status"], unique=False)
    op.create_index(
        "uq_admissions_encounter_live",
        "admissions",
        ["encounter_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    op.create_index(
        "uq_admissions_number_live",
        "admissions",
        ["hospital_id", "admission_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "bed_assignments",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("bed_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bed_class",
            sa.Enum(
                "GENERAL",
                "SEMI_PRIVATE",
                "PRIVATE",
                "DELUXE",
                "ICU",
                "HDU",
                "NICU",
                "EMERGENCY",
                "DAY_CARE",
                name="bedclass",
            ),
            nullable=False,
        ),
        sa.Column("tariff_item_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transfer_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
            name=op.f("fk_bed_assignments_admission_id_admissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
            name=op.f("fk_bed_assignments_assigned_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["bed_id"],
            ["beds.id"],
            name=op.f("fk_bed_assignments_bed_id_beds"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_bed_assignments_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_bed_assignments_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bed_assignments")),
    )
    op.create_index(
        op.f("ix_bed_assignments_admission_id"), "bed_assignments", ["admission_id"], unique=False
    )
    op.create_index(
        "ix_bed_assignments_admission_id_assigned_at",
        "bed_assignments",
        ["admission_id", "assigned_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bed_assignments_assigned_at"), "bed_assignments", ["assigned_at"], unique=False
    )
    op.create_index(
        op.f("ix_bed_assignments_bed_class"), "bed_assignments", ["bed_class"], unique=False
    )
    op.create_index(op.f("ix_bed_assignments_bed_id"), "bed_assignments", ["bed_id"], unique=False)
    op.create_index(
        op.f("ix_bed_assignments_deleted_at"), "bed_assignments", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_bed_assignments_hospital_id"), "bed_assignments", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_bed_assignments_patient_id"), "bed_assignments", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_bed_assignments_released_at"), "bed_assignments", ["released_at"], unique=False
    )
    op.create_index(
        "uq_bed_assignments_admission_live",
        "bed_assignments",
        ["admission_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND released_at IS NULL"),
    )
    op.create_index(
        "uq_bed_assignments_bed_live",
        "bed_assignments",
        ["bed_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND released_at IS NULL"),
    )
    op.create_table(
        "discharge_summaries",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("DRAFT", "FINAL", "AMENDED", name="summarystatus"), nullable=False
        ),
        sa.Column("presenting_complaint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diagnoses", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("history", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("examination", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("course_in_hospital", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("investigations", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("procedures", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("treatment_given", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "condition_at_discharge", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("discharge_medications", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("follow_up_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "diet_and_activity", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("warning_signs", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("follow_up_date", sa.Date(), nullable=True),
        sa.Column("compiled", sa.JSON(), nullable=True),
        sa.Column("compiled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_by_id", sa.Uuid(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_by_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "signatory_registration_number",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("amends_id", sa.Uuid(), nullable=True),
        sa.Column("amendment_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
            name=op.f("fk_discharge_summaries_admission_id_admissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["discharge_summaries.id"],
            name=op.f("fk_discharge_summaries_amends_id_discharge_summaries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_discharge_summaries_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_discharge_summaries_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_discharge_summaries_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signed_by_id"],
            ["users.id"],
            name=op.f("fk_discharge_summaries_signed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discharge_summaries")),
    )
    op.create_index(
        op.f("ix_discharge_summaries_admission_id"),
        "discharge_summaries",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_amends_id"), "discharge_summaries", ["amends_id"], unique=False
    )
    op.create_index(
        op.f("ix_discharge_summaries_deleted_at"),
        "discharge_summaries",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_encounter_id"),
        "discharge_summaries",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_follow_up_date"),
        "discharge_summaries",
        ["follow_up_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_hospital_id"),
        "discharge_summaries",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        "ix_discharge_summaries_hospital_id_status",
        "discharge_summaries",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_patient_id"),
        "discharge_summaries",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discharge_summaries_status"), "discharge_summaries", ["status"], unique=False
    )
    op.create_index(
        "uq_discharge_summaries_admission_live",
        "discharge_summaries",
        ["admission_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'AMENDED'"),
    )
    op.create_table(
        "medication_orders",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("drug_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("dose", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column(
            "route",
            sa.Enum(
                "ORAL",
                "IV",
                "IM",
                "SC",
                "TOPICAL",
                "INHALED",
                "RECTAL",
                "OPHTHALMIC",
                "NASOGASTRIC",
                "OTHER",
                name="medicationroute",
            ),
            nullable=False,
        ),
        sa.Column("frequency", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("times_per_day", sa.Integer(), nullable=False),
        sa.Column("dose_times", sa.JSON(), nullable=True),
        sa.Column("is_prn", sa.Boolean(), nullable=False),
        sa.Column("prn_indication", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "drug_schedule",
            sa.Enum("NONE", "H", "H1", "X", "NARCOTIC", name="drugschedule"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prescribed_by_id", sa.Uuid(), nullable=True),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_by_id", sa.Uuid(), nullable=True),
        sa.Column("stop_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
            name=op.f("fk_medication_orders_admission_id_admissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_medication_orders_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_medication_orders_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_medication_orders_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prescribed_by_id"],
            ["users.id"],
            name=op.f("fk_medication_orders_prescribed_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stopped_by_id"],
            ["users.id"],
            name=op.f("fk_medication_orders_stopped_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_orders")),
    )
    op.create_index(
        op.f("ix_medication_orders_admission_id"),
        "medication_orders",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        "ix_medication_orders_admission_id_is_active",
        "medication_orders",
        ["admission_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_orders_deleted_at"), "medication_orders", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_medication_orders_drug_name"), "medication_orders", ["drug_name"], unique=False
    )
    op.create_index(
        op.f("ix_medication_orders_drug_schedule"),
        "medication_orders",
        ["drug_schedule"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_orders_encounter_id"),
        "medication_orders",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_orders_hospital_id"), "medication_orders", ["hospital_id"], unique=False
    )
    op.create_index(
        "ix_medication_orders_hospital_id_is_active",
        "medication_orders",
        ["hospital_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_orders_is_active"), "medication_orders", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_medication_orders_is_prn"), "medication_orders", ["is_prn"], unique=False
    )
    op.create_index(
        op.f("ix_medication_orders_patient_id"), "medication_orders", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_medication_orders_prescribed_by_id"),
        "medication_orders",
        ["prescribed_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_orders_starts_at"), "medication_orders", ["starts_at"], unique=False
    )
    op.create_table(
        "medication_administrations",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("medication_order_id", sa.Uuid(), nullable=False),
        sa.Column("admission_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("drug_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("dose", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column(
            "route",
            sa.Enum(
                "ORAL",
                "IV",
                "IM",
                "SC",
                "TOPICAL",
                "INHALED",
                "RECTAL",
                "OPHTHALMIC",
                "NASOGASTRIC",
                "OTHER",
                name="medicationroute",
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DUE", "GIVEN", "MISSED", "REFUSED", "HELD", "CANCELLED", name="dosestatus"),
            nullable=False,
        ),
        sa.Column("administered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("administered_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "administered_by_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("auto_missed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["administered_by_id"],
            ["users.id"],
            name=op.f("fk_medication_administrations_administered_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["admissions.id"],
            name=op.f("fk_medication_administrations_admission_id_admissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_medication_administrations_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["medication_order_id"],
            ["medication_orders.id"],
            name=op.f("fk_medication_administrations_medication_order_id_medication_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_medication_administrations_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_administrations")),
    )
    op.create_index(
        op.f("ix_medication_administrations_administered_by_id"),
        "medication_administrations",
        ["administered_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_admission_id"),
        "medication_administrations",
        ["admission_id"],
        unique=False,
    )
    op.create_index(
        "ix_medication_administrations_admission_id_due_at",
        "medication_administrations",
        ["admission_id", "due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_auto_missed"),
        "medication_administrations",
        ["auto_missed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_deleted_at"),
        "medication_administrations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_due_at"),
        "medication_administrations",
        ["due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_hospital_id"),
        "medication_administrations",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        "ix_medication_administrations_hospital_id_due_at",
        "medication_administrations",
        ["hospital_id", "due_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_medication_order_id"),
        "medication_administrations",
        ["medication_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_patient_id"),
        "medication_administrations",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_administrations_status"),
        "medication_administrations",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_medication_administrations_status_due_at",
        "medication_administrations",
        ["status", "due_at"],
        unique=False,
    )
    op.create_index(
        "uq_medication_administrations_slot",
        "medication_administrations",
        ["medication_order_id", "due_at"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_medication_administrations_slot",
        table_name="medication_administrations",
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    op.drop_index(
        "ix_medication_administrations_status_due_at", table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_status"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_patient_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_medication_order_id"),
        table_name="medication_administrations",
    )
    op.drop_index(
        "ix_medication_administrations_hospital_id_due_at", table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_hospital_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_due_at"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_deleted_at"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_auto_missed"), table_name="medication_administrations"
    )
    op.drop_index(
        "ix_medication_administrations_admission_id_due_at", table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_admission_id"), table_name="medication_administrations"
    )
    op.drop_index(
        op.f("ix_medication_administrations_administered_by_id"),
        table_name="medication_administrations",
    )
    op.drop_table("medication_administrations")
    op.drop_index(op.f("ix_medication_orders_starts_at"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_prescribed_by_id"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_patient_id"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_is_prn"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_is_active"), table_name="medication_orders")
    op.drop_index("ix_medication_orders_hospital_id_is_active", table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_hospital_id"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_encounter_id"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_drug_schedule"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_drug_name"), table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_deleted_at"), table_name="medication_orders")
    op.drop_index("ix_medication_orders_admission_id_is_active", table_name="medication_orders")
    op.drop_index(op.f("ix_medication_orders_admission_id"), table_name="medication_orders")
    op.drop_table("medication_orders")
    op.drop_index(
        "uq_discharge_summaries_admission_live",
        table_name="discharge_summaries",
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'AMENDED'"),
    )
    op.drop_index(op.f("ix_discharge_summaries_status"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_patient_id"), table_name="discharge_summaries")
    op.drop_index("ix_discharge_summaries_hospital_id_status", table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_hospital_id"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_follow_up_date"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_encounter_id"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_deleted_at"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_amends_id"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_admission_id"), table_name="discharge_summaries")
    op.drop_table("discharge_summaries")
    op.drop_index(
        "uq_bed_assignments_bed_live",
        table_name="bed_assignments",
        postgresql_where=sa.text("deleted_at IS NULL AND released_at IS NULL"),
    )
    op.drop_index(
        "uq_bed_assignments_admission_live",
        table_name="bed_assignments",
        postgresql_where=sa.text("deleted_at IS NULL AND released_at IS NULL"),
    )
    op.drop_index(op.f("ix_bed_assignments_released_at"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_patient_id"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_hospital_id"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_deleted_at"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_bed_id"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_bed_class"), table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_assigned_at"), table_name="bed_assignments")
    op.drop_index("ix_bed_assignments_admission_id_assigned_at", table_name="bed_assignments")
    op.drop_index(op.f("ix_bed_assignments_admission_id"), table_name="bed_assignments")
    op.drop_table("bed_assignments")
    op.drop_index(
        "uq_admissions_number_live",
        table_name="admissions",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_admissions_encounter_live",
        table_name="admissions",
        postgresql_where=sa.text("deleted_at IS NULL AND status <> 'CANCELLED'"),
    )
    op.drop_index(op.f("ix_admissions_status"), table_name="admissions")
    op.drop_index("ix_admissions_patient_id_admitted_at", table_name="admissions")
    op.drop_index(op.f("ix_admissions_patient_id"), table_name="admissions")
    op.drop_index("ix_admissions_hospital_id_status", table_name="admissions")
    op.drop_index(op.f("ix_admissions_hospital_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_encounter_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_discharged_at"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_discharge_type"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_department_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_deleted_at"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_attending_doctor_id"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_admitted_at"), table_name="admissions")
    op.drop_index(op.f("ix_admissions_admission_number"), table_name="admissions")
    op.drop_table("admissions")
    op.drop_index(
        "uq_beds_code_live", table_name="beds", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index("ix_beds_ward_id_status", table_name="beds")
    op.drop_index(op.f("ix_beds_ward_id"), table_name="beds")
    op.drop_index(op.f("ix_beds_tariff_item_code"), table_name="beds")
    op.drop_index(op.f("ix_beds_status"), table_name="beds")
    op.drop_index(op.f("ix_beds_is_active"), table_name="beds")
    op.drop_index("ix_beds_hospital_id_bed_class_status", table_name="beds")
    op.drop_index(op.f("ix_beds_hospital_id"), table_name="beds")
    op.drop_index(op.f("ix_beds_deleted_at"), table_name="beds")
    op.drop_index(op.f("ix_beds_code"), table_name="beds")
    op.drop_index(op.f("ix_beds_bed_class"), table_name="beds")
    op.drop_table("beds")
    op.drop_index(
        "uq_wards_code_live", table_name="wards", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(op.f("ix_wards_name"), table_name="wards")
    op.drop_index(op.f("ix_wards_is_active"), table_name="wards")
    op.drop_index(op.f("ix_wards_hospital_id"), table_name="wards")
    op.drop_index(op.f("ix_wards_department_id"), table_name="wards")
    op.drop_index(op.f("ix_wards_deleted_at"), table_name="wards")
    op.drop_index(op.f("ix_wards_code"), table_name="wards")
    op.drop_index(op.f("ix_wards_bed_class"), table_name="wards")
    op.drop_table("wards")
    op.drop_index("uq_admission_sequences_hospital_year", table_name="admission_sequences")
    op.drop_index(op.f("ix_admission_sequences_year"), table_name="admission_sequences")
    op.drop_index(op.f("ix_admission_sequences_hospital_id"), table_name="admission_sequences")
    op.drop_table("admission_sequences")
    # ### end Alembic commands ###
