"""diagnostics schema

Revision ID: 3c03c7405b82
Revises: a3f7c21d9e04
Create Date: 2026-08-08 20:01:00.000000+00:00

The test catalogue and its analytes and reference bands, the specimen, and the
report with its result values.

There is deliberately no diagnostics-side order table: `diagnostic_reports` and
`specimens` both hang off the existing `clinical.orders` row, so "what was asked
for" has exactly one answer.

Row-level security and this module's permission seed land in the migration that
follows, on the pattern the earlier module migrations set.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "3c03c7405b82"
down_revision: str | None = "a3f7c21d9e04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accession_sequences",
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_accession_sequences_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accession_sequences")),
    )
    op.create_index(
        op.f("ix_accession_sequences_hospital_id"),
        "accession_sequences",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accession_sequences_year"), "accession_sequences", ["year"], unique=False
    )
    op.create_index(
        "uq_accession_sequences_hospital_year_kind",
        "accession_sequences",
        ["hospital_id", "year", "kind"],
        unique=True,
    )
    op.create_table(
        "test_catalogue_items",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "discipline", sa.Enum("LAB", "RADIOLOGY", name="diagnosticdiscipline"), nullable=False
        ),
        sa.Column("section", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column(
            "specimen_type",
            sa.Enum(
                "BLOOD",
                "SERUM",
                "PLASMA",
                "URINE",
                "STOOL",
                "SPUTUM",
                "SWAB",
                "TISSUE",
                "CSF",
                "FLUID",
                "NONE",
                name="specimentype",
            ),
            nullable=False,
        ),
        sa.Column("container", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("turnaround_minutes", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("preparation_notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_test_catalogue_items_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_test_catalogue_items_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_catalogue_items")),
    )
    op.create_index(
        op.f("ix_test_catalogue_items_code"), "test_catalogue_items", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_test_catalogue_items_deleted_at"),
        "test_catalogue_items",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_catalogue_items_department_id"),
        "test_catalogue_items",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_catalogue_items_discipline"),
        "test_catalogue_items",
        ["discipline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_catalogue_items_hospital_id"),
        "test_catalogue_items",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        "ix_test_catalogue_items_hospital_id_discipline",
        "test_catalogue_items",
        ["hospital_id", "discipline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_catalogue_items_is_active"),
        "test_catalogue_items",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_catalogue_items_name"), "test_catalogue_items", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_test_catalogue_items_section"), "test_catalogue_items", ["section"], unique=False
    )
    op.create_index(
        "uq_test_catalogue_items_code_live",
        "test_catalogue_items",
        ["hospital_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "test_analytes",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("catalogue_item_id", sa.Uuid(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_numeric", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalogue_item_id"],
            ["test_catalogue_items.id"],
            name=op.f("fk_test_analytes_catalogue_item_id_test_catalogue_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_test_analytes_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_analytes")),
    )
    op.create_index(
        op.f("ix_test_analytes_catalogue_item_id"),
        "test_analytes",
        ["catalogue_item_id"],
        unique=False,
    )
    op.create_index(op.f("ix_test_analytes_code"), "test_analytes", ["code"], unique=False)
    op.create_index(
        op.f("ix_test_analytes_deleted_at"), "test_analytes", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_test_analytes_hospital_id"), "test_analytes", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_analytes_is_active"), "test_analytes", ["is_active"], unique=False
    )
    op.create_index(
        "uq_test_analytes_code_live",
        "test_analytes",
        ["catalogue_item_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "reference_ranges",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analyte_id", sa.Uuid(), nullable=False),
        sa.Column("sex", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("age_min_years", sa.Integer(), nullable=True),
        sa.Column("age_max_years", sa.Integer(), nullable=True),
        sa.Column("low", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("critical_low", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("critical_high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("text_range", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["analyte_id"],
            ["test_analytes.id"],
            name=op.f("fk_reference_ranges_analyte_id_test_analytes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_reference_ranges_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_ranges")),
    )
    op.create_index(
        op.f("ix_reference_ranges_analyte_id"), "reference_ranges", ["analyte_id"], unique=False
    )
    op.create_index(
        "ix_reference_ranges_analyte_id_sex",
        "reference_ranges",
        ["analyte_id", "sex"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_ranges_deleted_at"), "reference_ranges", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_reference_ranges_hospital_id"), "reference_ranges", ["hospital_id"], unique=False
    )
    op.create_table(
        "specimens",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("accession_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column(
            "specimen_type",
            sa.Enum(
                "BLOOD",
                "SERUM",
                "PLASMA",
                "URINE",
                "STOOL",
                "SPUTUM",
                "SWAB",
                "TISSUE",
                "CSF",
                "FLUID",
                "NONE",
                name="specimentype",
            ),
            nullable=False,
        ),
        sa.Column("container", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_COLLECTION",
                "COLLECTED",
                "RECEIVED",
                "REJECTED",
                "CANCELLED",
                name="specimenstatus",
            ),
            nullable=False,
        ),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_by_id", sa.Uuid(), nullable=True),
        sa.Column("collection_site", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_by_id", sa.Uuid(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["collected_by_id"],
            ["users.id"],
            name=op.f("fk_specimens_collected_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_specimens_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_specimens_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_specimens_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"],
            ["users.id"],
            name=op.f("fk_specimens_received_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specimens")),
    )
    op.create_index(
        op.f("ix_specimens_accession_number"), "specimens", ["accession_number"], unique=False
    )
    op.create_index(op.f("ix_specimens_deleted_at"), "specimens", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_specimens_hospital_id"), "specimens", ["hospital_id"], unique=False)
    op.create_index(
        "ix_specimens_hospital_id_status", "specimens", ["hospital_id", "status"], unique=False
    )
    op.create_index(op.f("ix_specimens_order_id"), "specimens", ["order_id"], unique=False)
    op.create_index(op.f("ix_specimens_patient_id"), "specimens", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_specimens_specimen_type"), "specimens", ["specimen_type"], unique=False
    )
    op.create_index(op.f("ix_specimens_status"), "specimens", ["status"], unique=False)
    op.create_index(
        "uq_specimens_accession_live",
        "specimens",
        ["hospital_id", "accession_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "diagnostic_reports",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_number", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("catalogue_item_id", sa.Uuid(), nullable=True),
        sa.Column("specimen_id", sa.Uuid(), nullable=True),
        sa.Column(
            "discipline", sa.Enum("LAB", "RADIOLOGY", name="diagnosticdiscipline"), nullable=False
        ),
        sa.Column("test_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REGISTERED",
                "IN_PROGRESS",
                "PRELIMINARY",
                "FINAL",
                "AMENDED",
                "CANCELLED",
                name="reportstatus",
            ),
            nullable=False,
        ),
        sa.Column("findings", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("impression", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("technique", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entered_by_id", sa.Uuid(), nullable=True),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "verifier_registration_number",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("has_critical_result", sa.Boolean(), nullable=False),
        sa.Column("critical_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("critical_notified_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "critical_notified_to", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("amends_id", sa.Uuid(), nullable=True),
        sa.Column("amendment_reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "cancellation_reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["amends_id"],
            ["diagnostic_reports.id"],
            name=op.f("fk_diagnostic_reports_amends_id_diagnostic_reports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["catalogue_item_id"],
            ["test_catalogue_items.id"],
            name=op.f("fk_diagnostic_reports_catalogue_item_id_test_catalogue_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["critical_notified_by_id"],
            ["users.id"],
            name=op.f("fk_diagnostic_reports_critical_notified_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
            name=op.f("fk_diagnostic_reports_encounter_id_encounters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_id"],
            ["users.id"],
            name=op.f("fk_diagnostic_reports_entered_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_diagnostic_reports_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_diagnostic_reports_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_diagnostic_reports_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["specimen_id"],
            ["specimens.id"],
            name=op.f("fk_diagnostic_reports_specimen_id_specimens"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_id"],
            ["users.id"],
            name=op.f("fk_diagnostic_reports_verified_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_reports")),
    )
    op.create_index(
        op.f("ix_diagnostic_reports_amends_id"), "diagnostic_reports", ["amends_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_reports_catalogue_item_id"),
        "diagnostic_reports",
        ["catalogue_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_deleted_at"), "diagnostic_reports", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_reports_discipline"), "diagnostic_reports", ["discipline"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_reports_encounter_id"),
        "diagnostic_reports",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_has_critical_result"),
        "diagnostic_reports",
        ["has_critical_result"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_hospital_id"),
        "diagnostic_reports",
        ["hospital_id"],
        unique=False,
    )
    op.create_index(
        "ix_diagnostic_reports_hospital_id_status",
        "diagnostic_reports",
        ["hospital_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_order_id"), "diagnostic_reports", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_reports_patient_id"), "diagnostic_reports", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_diagnostic_reports_patient_id_created_at",
        "diagnostic_reports",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_report_number"),
        "diagnostic_reports",
        ["report_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_specimen_id"),
        "diagnostic_reports",
        ["specimen_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_reports_status"), "diagnostic_reports", ["status"], unique=False
    )
    op.create_index(
        "uq_diagnostic_reports_number_live",
        "diagnostic_reports",
        ["hospital_id", "report_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_diagnostic_reports_order_live",
        "diagnostic_reports",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status NOT IN ('AMENDED', 'CANCELLED')"),
    )
    op.create_table(
        "result_values",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hospital_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("analyte_id", sa.Uuid(), nullable=True),
        sa.Column("analyte_code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("value_numeric", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("value_text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("ref_low", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ref_high", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("ref_text", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column(
            "flag",
            sa.Enum(
                "NORMAL",
                "LOW",
                "HIGH",
                "CRITICAL_LOW",
                "CRITICAL_HIGH",
                "ABNORMAL",
                name="resultflag",
            ),
            nullable=False,
        ),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["analyte_id"],
            ["test_analytes.id"],
            name=op.f("fk_result_values_analyte_id_test_analytes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
            name=op.f("fk_result_values_hospital_id_hospitals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_result_values_patient_id_patients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["diagnostic_reports.id"],
            name=op.f("fk_result_values_report_id_diagnostic_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_result_values")),
    )
    op.create_index(
        op.f("ix_result_values_analyte_code"), "result_values", ["analyte_code"], unique=False
    )
    op.create_index(
        op.f("ix_result_values_analyte_id"), "result_values", ["analyte_id"], unique=False
    )
    op.create_index(
        op.f("ix_result_values_deleted_at"), "result_values", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_result_values_flag"), "result_values", ["flag"], unique=False)
    op.create_index(
        op.f("ix_result_values_hospital_id"), "result_values", ["hospital_id"], unique=False
    )
    op.create_index(
        op.f("ix_result_values_is_critical"), "result_values", ["is_critical"], unique=False
    )
    op.create_index(
        op.f("ix_result_values_patient_id"), "result_values", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_result_values_patient_id_analyte_code",
        "result_values",
        ["patient_id", "analyte_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_result_values_report_id"), "result_values", ["report_id"], unique=False
    )
    op.create_index(
        "ix_result_values_report_id_display_order",
        "result_values",
        ["report_id", "display_order"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_result_values_report_id_display_order", table_name="result_values")
    op.drop_index(op.f("ix_result_values_report_id"), table_name="result_values")
    op.drop_index("ix_result_values_patient_id_analyte_code", table_name="result_values")
    op.drop_index(op.f("ix_result_values_patient_id"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_is_critical"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_hospital_id"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_flag"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_deleted_at"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_analyte_id"), table_name="result_values")
    op.drop_index(op.f("ix_result_values_analyte_code"), table_name="result_values")
    op.drop_table("result_values")
    op.drop_index(
        "uq_diagnostic_reports_order_live",
        table_name="diagnostic_reports",
        postgresql_where=sa.text("deleted_at IS NULL AND status NOT IN ('AMENDED', 'CANCELLED')"),
    )
    op.drop_index(
        "uq_diagnostic_reports_number_live",
        table_name="diagnostic_reports",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_diagnostic_reports_status"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_specimen_id"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_report_number"), table_name="diagnostic_reports")
    op.drop_index("ix_diagnostic_reports_patient_id_created_at", table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_patient_id"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_order_id"), table_name="diagnostic_reports")
    op.drop_index("ix_diagnostic_reports_hospital_id_status", table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_hospital_id"), table_name="diagnostic_reports")
    op.drop_index(
        op.f("ix_diagnostic_reports_has_critical_result"), table_name="diagnostic_reports"
    )
    op.drop_index(op.f("ix_diagnostic_reports_encounter_id"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_discipline"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_deleted_at"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_catalogue_item_id"), table_name="diagnostic_reports")
    op.drop_index(op.f("ix_diagnostic_reports_amends_id"), table_name="diagnostic_reports")
    op.drop_table("diagnostic_reports")
    op.drop_index(
        "uq_specimens_accession_live",
        table_name="specimens",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_specimens_status"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_specimen_type"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_patient_id"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_order_id"), table_name="specimens")
    op.drop_index("ix_specimens_hospital_id_status", table_name="specimens")
    op.drop_index(op.f("ix_specimens_hospital_id"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_deleted_at"), table_name="specimens")
    op.drop_index(op.f("ix_specimens_accession_number"), table_name="specimens")
    op.drop_table("specimens")
    op.drop_index(op.f("ix_reference_ranges_hospital_id"), table_name="reference_ranges")
    op.drop_index(op.f("ix_reference_ranges_deleted_at"), table_name="reference_ranges")
    op.drop_index("ix_reference_ranges_analyte_id_sex", table_name="reference_ranges")
    op.drop_index(op.f("ix_reference_ranges_analyte_id"), table_name="reference_ranges")
    op.drop_table("reference_ranges")
    op.drop_index(
        "uq_test_analytes_code_live",
        table_name="test_analytes",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_test_analytes_is_active"), table_name="test_analytes")
    op.drop_index(op.f("ix_test_analytes_hospital_id"), table_name="test_analytes")
    op.drop_index(op.f("ix_test_analytes_deleted_at"), table_name="test_analytes")
    op.drop_index(op.f("ix_test_analytes_code"), table_name="test_analytes")
    op.drop_index(op.f("ix_test_analytes_catalogue_item_id"), table_name="test_analytes")
    op.drop_table("test_analytes")
    op.drop_index(
        "uq_test_catalogue_items_code_live",
        table_name="test_catalogue_items",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_test_catalogue_items_section"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_name"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_is_active"), table_name="test_catalogue_items")
    op.drop_index(
        "ix_test_catalogue_items_hospital_id_discipline", table_name="test_catalogue_items"
    )
    op.drop_index(op.f("ix_test_catalogue_items_hospital_id"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_discipline"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_department_id"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_deleted_at"), table_name="test_catalogue_items")
    op.drop_index(op.f("ix_test_catalogue_items_code"), table_name="test_catalogue_items")
    op.drop_table("test_catalogue_items")
    op.drop_index("uq_accession_sequences_hospital_year_kind", table_name="accession_sequences")
    op.drop_index(op.f("ix_accession_sequences_year"), table_name="accession_sequences")
    op.drop_index(op.f("ix_accession_sequences_hospital_id"), table_name="accession_sequences")
    op.drop_table("accession_sequences")
    # ### end Alembic commands ###

    # Alembic drops tables but never the enum types they created, so a
    # downgrade/upgrade cycle otherwise fails with "type already exists".
    for enum_name in (
        "reportstatus",
        "resultflag",
        "specimenstatus",
        "specimentype",
        "diagnosticdiscipline",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
